import json
import tempfile
import unittest
from pathlib import Path

from app.pipeline.intake_parser import run_intake_parser
from app.pipeline.layer_builder import build_layers
from app.pipeline.viewpoint_runner import run_viewpoints
from app.state.workspace_manager import WorkspaceManager
from app.validation.artifact_contract_validator import read_frontmatter_document, validate_artifact_contract


class IntakeLayersViewpointsTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)

        # copy required schema for artifact contract
        schema_src = Path(__file__).resolve().parents[1] / "schemas" / "artifact_frontmatter.schema.json"
        schema_dst = self.root / "schemas"
        schema_dst.mkdir(parents=True, exist_ok=True)
        (schema_dst / "artifact_frontmatter.schema.json").write_text(
            schema_src.read_text(encoding="utf-8"),
            encoding="utf-8",
        )

        self.manager = WorkspaceManager(self.root)
        self.ref = self.manager.create_workspace("case_20260303_201")

        (self.ref.path / "raw" / "case_input.md").write_text(
            """
Project has strategy risks. Team needs clear owner and process.
Must reduce cost and should improve product quality.
Operational process has bottleneck in delivery stage.
""".strip()
            + "\n",
            encoding="utf-8",
        )

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def test_s2_t1_intake_outputs(self):
        out = run_intake_parser(self.root, self.ref.workspace_id)
        self.assertEqual(out["source_count"], 1)
        self.assertTrue((self.ref.path / "intake" / "source_manifest.json").is_file())
        self.assertTrue((self.ref.path / "intake" / "normalized_case.md").is_file())

        manifest = json.loads((self.ref.path / "intake" / "source_manifest.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["total_sources"], 1)

        contract = validate_artifact_contract(
            project_root=self.root,
            artifact_path=self.ref.path / "intake" / "normalized_case.md",
            workspace_path=self.ref.path,
        )
        self.assertTrue(contract.is_valid)

    def test_s2_t2_layers_outputs(self):
        run_intake_parser(self.root, self.ref.workspace_id)
        out = build_layers(self.root, self.ref.workspace_id, llm_mode="local")
        self.assertIn("layer_1_business_model.md", out["layers"])
        self.assertTrue((self.ref.path / "layers" / "trace_links.json").is_file())

        for name in out["layers"]:
            p = self.ref.path / "layers" / name
            self.assertTrue(p.is_file())
            self.assertIn("Generated by local-llm mode.", p.read_text(encoding="utf-8"))
            contract = validate_artifact_contract(self.root, p, self.ref.path)
            self.assertTrue(contract.is_valid)

    def test_s2_t3_viewpoints_outputs(self):
        run_intake_parser(self.root, self.ref.workspace_id)
        build_layers(self.root, self.ref.workspace_id, llm_mode="local")
        out = run_viewpoints(self.root, self.ref.workspace_id, llm_mode="local")

        self.assertEqual(out["viewpoint_count"], 6)
        self.assertTrue((self.ref.path / "viewpoints" / "conflicts_index.md").is_file())
        self.assertEqual(out["domain_profile"], "analysis/domain_profile.json")

        profile_path = self.ref.path / "analysis" / "domain_profile.json"
        self.assertTrue(profile_path.is_file())
        profile = json.loads(profile_path.read_text(encoding="utf-8"))
        self.assertEqual(profile["workspace_id"], self.ref.workspace_id)
        self.assertTrue(profile["domain_axes"])
        self.assertTrue(profile["allowed_ontological_domains"])
        self.assertIn("reasoning_scope", profile)

        for vp in ["strategist", "analyst", "operator", "architect", "critic", "client"]:
            p = self.ref.path / "viewpoints" / f"{vp}.md"
            self.assertTrue(p.is_file())
            txt = p.read_text(encoding="utf-8")
            for section in [
                "## viewpoint_name",
                "## primary_concerns",
                "## layer_findings",
                "## key_risks",
                "## supported_actions",
                "## objections",
                "## evidence_gaps",
                "## non_negotiables",
            ]:
                self.assertIn(section, txt)
            self.assertIn("Generated by local-llm mode.", txt)
            doc = read_frontmatter_document(p)
            self.assertEqual(doc.frontmatter.get("epistemic_status"), "inferred")

            contract = validate_artifact_contract(self.root, p, self.ref.path)
            self.assertTrue(contract.is_valid)

    def test_vp_skill_directories_exist(self):
        project_root = Path(__file__).resolve().parents[1]
        expected = [
            "ec-vp-strategist",
            "ec-vp-analyst",
            "ec-vp-operator",
            "ec-vp-architect",
            "ec-vp-critic",
            "ec-vp-client",
            "ec-vp-market",
        ]
        for name in expected:
            skill = project_root / ".agent" / "skills" / name / "SKILL.md"
            self.assertTrue(skill.is_file(), str(skill))


if __name__ == "__main__":
    unittest.main()
