import unittest
import tempfile
import json
from pathlib import Path
from unittest.mock import patch

from app.pipeline.intake_parser import run_intake_parser
from app.pipeline.layer_builder import build_layers
from app.pipeline.viewpoint_runner import run_viewpoints
from app.pipeline.characterization import run_characterization
from app.pipeline.problem_factory import run_problem_factory
from app.state.workspace_manager import WorkspaceManager
from app.validation.artifact_contract_validator import validate_artifact_contract


class CharacterizationProblemFactoryTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)

        schema_src = Path(__file__).resolve().parents[1] / "schemas" / "artifact_frontmatter.schema.json"
        schema_dst = self.root / "schemas"
        schema_dst.mkdir(parents=True, exist_ok=True)
        (schema_dst / "artifact_frontmatter.schema.json").write_text(
            schema_src.read_text(encoding="utf-8"),
            encoding="utf-8",
        )

        # copy required skills for llm-local pipeline
        skills_src = Path(__file__).resolve().parents[1] / ".agent" / "skills"
        skills_dst = self.root / ".agent" / "skills"
        skills_dst.mkdir(parents=True, exist_ok=True)
        for p in skills_src.glob("*/SKILL.md"):
            target = skills_dst / p.parent.name
            target.mkdir(parents=True, exist_ok=True)
            (target / "SKILL.md").write_text(p.read_text(encoding="utf-8"), encoding="utf-8")

        self.manager = WorkspaceManager(self.root)
        self.ref = self.manager.create_workspace("case_20260303_301")

        (self.ref.path / "raw" / "case_input.md").write_text(
            (
                "Project strategy is unstable and requires investor confidence.\n"
                "Team must define owner roles and constraints.\n"
                "Process has bottleneck in production stage.\n"
            ),
            encoding="utf-8",
        )

        run_intake_parser(self.root, self.ref.workspace_id)
        build_layers(self.root, self.ref.workspace_id, llm_mode="local")
        run_viewpoints(self.root, self.ref.workspace_id, llm_mode="local")

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def test_s3_t1_characterization_outputs(self):
        out = run_characterization(self.root, self.ref.workspace_id, llm_mode="local")
        self.assertTrue((self.ref.path / "characterization" / "CharacterizationPassport.md").is_file())
        self.assertTrue((self.ref.path / "characterization" / "IndicatorSet.md").is_file())
        self.assertTrue((self.ref.path / "characterization" / "ParityPlan.md").is_file())
        self.assertGreaterEqual(len(out["characteristic_cards"]), 3)

        text = (self.ref.path / "characterization" / "CharacterizationPassport.md").read_text(encoding="utf-8")
        self.assertIn("anti_goodhart", text.lower())
        self.assertIn("Generated by local-llm mode.", text)

        for rel in [
            "characterization/CharacterizationPassport.md",
            "characterization/IndicatorSet.md",
            "characterization/ParityPlan.md",
        ]:
            res = validate_artifact_contract(self.root, self.ref.path / rel, self.ref.path)
            self.assertTrue(res.is_valid, rel)

        graph = json.loads((self.ref.path / "analysis" / "epistemic_graph.json").read_text(encoding="utf-8"))
        node_types = {node["node_type"] for node in graph["nodes"]}
        self.assertIn("source_fact", node_types)
        self.assertIn("derived_metric", node_types)
        self.assertIn("normative_target", node_types)

        ledger = (self.ref.path / "governance" / "epistemic_ledger.jsonl").read_text(encoding="utf-8")
        self.assertIn("claim_created", ledger)

    def test_s3_t2_t3_problem_factory_outputs(self):
        run_characterization(self.root, self.ref.workspace_id, llm_mode="local")
        out = run_problem_factory(self.root, self.ref.workspace_id, llm_mode="local")

        expected = [
            "problems/ProblemArchive.md",
            "problems/ProblemPortfolio.md",
            "problems/SelectedProblemCard.md",
            "problems/ComparisonAcceptanceSpec.md",
        ]
        for rel in expected:
            p = self.ref.path / rel
            self.assertTrue(p.is_file(), rel)
            res = validate_artifact_contract(self.root, p, self.ref.path)
            self.assertTrue(res.is_valid, rel)

        archive_text = (self.ref.path / "problems" / "ProblemArchive.md").read_text(encoding="utf-8")
        self.assertIn("goldilocks_score", archive_text)

        portfolio_text = (self.ref.path / "problems" / "ProblemPortfolio.md").read_text(encoding="utf-8")
        self.assertIn("Selected for current cycle", portfolio_text)

        card_text = (self.ref.path / "problems" / "SelectedProblemCard.md").read_text(encoding="utf-8")
        self.assertIn("problem_id", card_text)
        self.assertIn("evidence_refs", card_text)

        spec_text = (self.ref.path / "problems" / "ComparisonAcceptanceSpec.md").read_text(encoding="utf-8")
        self.assertIn("hard_constraints", spec_text)
        self.assertIn("selection_policy", spec_text)

        self.assertIn("comparison_acceptance_spec", out)

        graph = json.loads((self.ref.path / "analysis" / "epistemic_graph.json").read_text(encoding="utf-8"))
        node_types = {node["node_type"] for node in graph["nodes"]}
        edge_types = {edge["edge_type"] for edge in graph["edges"]}
        self.assertIn("problem", node_types)
        self.assertIn("decision_constraint", node_types)
        self.assertTrue(edge_types & {"DERIVED_FROM", "CONSTRAINS", "SUPPORTS", "RELATES_TO"})

        hypotheses = [node for node in graph["nodes"] if node["node_type"] == "hypothesis"]
        self.assertTrue(hypotheses)
        self.assertFalse(any("Hypotheses to Validate" in node["statement"] and node["node_type"] == "source_fact" for node in graph["nodes"]))

        ledger = (self.ref.path / "governance" / "epistemic_ledger.jsonl").read_text(encoding="utf-8")
        self.assertIn("constraint_compiled", ledger)

    def test_s3_t4_skill_prompts_exist(self):
        project_root = Path(__file__).resolve().parents[1]
        expected = [
            ".agent/skills/ec-characterization/SKILL.md",
            ".agent/skills/ec-problem-factory/SKILL.md",
        ]
        for rel in expected:
            self.assertTrue((project_root / rel).is_file(), rel)

    def test_s3_problem_factory_unwraps_embedded_markdown(self):
        run_characterization(self.root, self.ref.workspace_id, llm_mode="local")
        wrapped = """
Вступительный текст, который не должен попасть в итоговый артефакт.

```markdown
---
id: wrapped
artifact_type: problem_archive
---
# Clean Problem Artifact

- goldilocks_score: 0.8
- selection_policy: keep
```
"""
        with patch("app.pipeline.problem_factory.generate_markdown_with_skill", return_value=wrapped):
            out = run_problem_factory(self.root, self.ref.workspace_id, llm_mode="local")

        archive_text = (self.ref.path / "problems" / "ProblemArchive.md").read_text(encoding="utf-8")
        self.assertIn("# Clean Problem Artifact", archive_text)
        self.assertNotIn("```markdown", archive_text)
        self.assertNotIn("Вступительный текст", archive_text)
        self.assertIn("archive", out)


if __name__ == "__main__":
    unittest.main()
