from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Tuple

from app.llm.client import generate_markdown_with_skill
from app.pipeline.artifact_template import build_frontmatter, write_markdown_artifact


def _load_skill(project_root: Path) -> str:
    p = project_root / ".agent" / "skills" / "ec-conflict-router" / "SKILL.md"
    if p.is_file():
        return p.read_text(encoding="utf-8")
    return "name: ec-conflict-router\ndescription: conflict routing"


RULES: List[Tuple[str, str, str]] = [
    ("quality-attribute conflict", "ATAM", "quality/safety/performance tradeoff requires architectural method"),
    ("alternative ranking conflict", "MCDA", "ranking dispute needs explicit weighted comparison"),
    ("stakeholder conflict", "WinWin", "stakeholder alignment via negotiated agreement"),
    ("uncertainty conflict", "Delphi", "low-confidence evidence requires iterative expert convergence"),
    ("scope-set conflict", "SBCE", "preserve optionality and narrow by evidence over time"),
]
FALLBACK_METHOD = "Delphi"
FALLBACK_RATIONALE = "unsupported conflict type routed to controlled fallback method"


def _classify_conflict(text: str) -> str:
    low = text.lower()
    if any(x in low for x in ["performance", "latency", "reliability", "quality", "safety", "security"]):
        return "quality-attribute conflict"
    if any(x in low for x in ["priority", "ranking", "rank", "weight", "score"]):
        return "alternative ranking conflict"
    if any(x in low for x in ["stakeholder", "client", "owner", "operator", "team"]):
        return "stakeholder conflict"
    if any(x in low for x in ["unknown", "uncertain", "no data", "insufficient evidence", "assumption"]):
        return "uncertainty conflict"
    if any(x in low for x in ["scope", "option", "variant", "alternative", "portfolio"]):
        return "scope-set conflict"
    return "unsupported"


def _method_for_conflict(conflict_type: str) -> Tuple[str, str]:
    for c_type, method, rationale in RULES:
        if c_type == conflict_type:
            return method, rationale
    return FALLBACK_METHOD, FALLBACK_RATIONALE


def _extract_conflict_lines(conflicts_index_text: str) -> List[str]:
    lines: List[str] = []
    for ln in conflicts_index_text.splitlines():
        s = ln.strip()
        if s.startswith("- "):
            content = s[2:].strip()
            if content and "no explicit conflicts" not in content.lower():
                lines.append(content)
    return lines


def _build_conflict_records_markdown(conflict_lines: List[str]) -> str:
    if not conflict_lines:
        conflict_lines = ["no explicit conflicts provided; uncertainty and ranking risks remain"]

    parts: List[str] = ["# Conflict Records", ""]
    for idx, line in enumerate(conflict_lines, start=1):
        conflict_type = _classify_conflict(line)
        method, rationale = _method_for_conflict(conflict_type)
        parts.extend(
            [
                f"## conflict_{idx:02d}",
                f"- conflict_type: {conflict_type}",
                "- layers_involved: requirements,functional",
                "- viewpoints_involved: strategist,analyst,architect,operator,client",
                f"- source_text: {line}",
                f"- method_selected: {method}",
                f"- selection_rationale: {rationale}",
                "- resolution_status: routed",
                "",
            ]
        )
    parts.append("_Generated by conflict-router rules._")
    return "\n".join(parts)


def run_conflict_router(project_root: Path, workspace_id: str, llm_mode: str = "local") -> Dict[str, object]:
    workspace = project_root / "cases" / workspace_id
    out_dir = workspace / "solutions"
    out_dir.mkdir(parents=True, exist_ok=True)

    parity_report = workspace / "solutions" / "ParityReport.md"
    tradeoff = workspace / "solutions" / "TradeoffTable.md"
    conflicts_index = workspace / "viewpoints" / "conflicts_index.md"
    if not parity_report.is_file() or not tradeoff.is_file() or not conflicts_index.is_file():
        raise ValueError("CONFLICT_ROUTER_REQUIRES_PARITY_AND_VIEWPOINT_CONFLICTS")

    conflicts_text = conflicts_index.read_text(encoding="utf-8")
    routed_conflicts = _extract_conflict_lines(conflicts_text)
    body = _build_conflict_records_markdown(routed_conflicts)

    # Optional LLM rendering in openai mode, deterministic router result is used as fallback.
    if llm_mode.lower() == "openai":
        skill_prompt = _load_skill(project_root)
        maybe_llm = generate_markdown_with_skill(
            system_skill_prompt=skill_prompt,
            user_payload={
                "task_type": "build_conflict_routing",
                "workspace_id": workspace_id,
                "parity_report": parity_report.read_text(encoding="utf-8"),
                "tradeoff_table": tradeoff.read_text(encoding="utf-8"),
                "viewpoint_conflicts": conflicts_text,
                "routed_conflicts": body,
            },
            mode=llm_mode,
        )
        if maybe_llm.strip():
            body = maybe_llm

    if "method_selected:" not in body or "selection_rationale:" not in body:
        raise ValueError("CONFLICT_ROUTER_INVALID_OUTPUT_MISSING_METHOD_OR_RATIONALE")

    fm = build_frontmatter(
        artifact_id=f"{workspace_id}__conflict_records",
        artifact_type="conflict_records",
        stage="solution_factory",
        parent_refs=[
            "solutions/ParityReport.md",
            "solutions/TradeoffTable.md",
            "viewpoints/conflicts_index.md",
        ],
        source_refs=["viewpoints/conflicts_index.md:L1"],
        evidence_refs=["solutions/ParityReport.md:L1"],
        next_expected_artifacts=["solutions/SelectedSolutions.md"],
    )
    write_markdown_artifact(out_dir / "ConflictRecords.md", fm, body)

    return {
        "workspace_id": workspace_id,
        "conflict_records": "solutions/ConflictRecords.md",
        "llm_mode": llm_mode,
    }
