from __future__ import annotations

import json
import os
import subprocess
import time
import urllib.error
import urllib.request
from typing import Any, Dict, List


def _extract_lines(text: str) -> List[str]:
    return [ln.strip() for ln in text.splitlines() if ln.strip() and not ln.strip().startswith("#")]


def _local_build_layer(payload: Dict[str, Any]) -> str:
    layer = payload.get("layer_name", "layer")
    normalized_case = str(payload.get("normalized_case", ""))
    lines = _extract_lines(normalized_case)

    def pick(keys: List[str], fallback: str) -> List[str]:
        picked = [ln for ln in lines if any(k in ln.lower() for k in keys)]
        return picked[:8] if picked else [fallback]

    if layer == "layer_1_business_model":
        points = pick(["value", "client", "market", "strategy", "цінн", "рин"], "GAP: business context is weak")
        title = "# Layer 1: Business Model"
    elif layer == "layer_2_requirements":
        points = pick(["must", "should", "need", "require", "треб", "повин", "необхід"], "GAP: requirements not explicit")
        title = "# Layer 2: Requirements"
    elif layer == "layer_3_functional_model":
        points = pick(["process", "flow", "stage", "function", "процес", "етап", "вироб"], "GAP: functional flow unclear")
        title = "# Layer 3: Functional Model"
    else:
        points = pick(["role", "owner", "team", "manager", "правл", "команд", "роль"], "GAP: allocation ownership undefined")
        title = "# Layer 4: Allocation Model"

    return title + "\n\n" + "\n".join(f"- {x}" for x in points) + "\n\n_Generated by local-llm mode._"


def _local_build_viewpoint(payload: Dict[str, Any]) -> str:
    viewpoint = str(payload.get("viewpoint", "viewpoint"))
    focus = str(payload.get("focus", ""))
    layers = payload.get("layers", {})

    def first_line(key: str) -> str:
        txt = str(layers.get(key, ""))
        lines = _extract_lines(txt)
        return lines[0] if lines else "no data"

    l1 = first_line("layer_1")
    l2 = first_line("layer_2")
    l3 = first_line("layer_3")
    l4 = first_line("layer_4")

    gaps = []
    for k, v in layers.items():
        if "GAP:" in str(v):
            gaps.append(f"{k} has unresolved GAP")

    objections = [f"Potential risk from {viewpoint} perspective"]
    if gaps:
        objections.append("Unresolved GAPs reduce decision confidence")

    body = [
        f"# Viewpoint: {viewpoint}",
        "",
        "## viewpoint_name",
        viewpoint,
        "",
        "## primary_concerns",
        f"- {focus}",
        "- preserve traceability and evidence quality",
        "",
        "## layer_findings",
        f"- layer_1: {l1}",
        f"- layer_2: {l2}",
        f"- layer_3: {l3}",
        f"- layer_4: {l4}",
        "",
        "## key_risks",
        "- decision under incomplete data",
        "- cross-layer inconsistency",
        "",
        "## supported_actions",
        "- proceed with explicit assumptions register",
        "",
        "## objections",
        *[f"- {x}" for x in objections],
        "",
        "## evidence_gaps",
        *( [f"- {g}" for g in gaps] if gaps else ["- none"] ),
        "",
        "## non_negotiables",
        "- do not skip acceptance constraints",
        "- keep links to source evidence",
        "",
        "_Generated by local-llm mode._",
    ]
    return "\n".join(body)


def _local_build_characterization(payload: Dict[str, Any]) -> str:
    viewpoint_summary = str(payload.get("viewpoint_summary", ""))
    layer_summary = str(payload.get("layer_summary", ""))
    weak_hint = "investment_status" if "invest" in viewpoint_summary.lower() else "team_alignment"
    return (
        "# Characterization Passport\n\n"
        "## optimization_goals\n"
        "- reduce strategic uncertainty and improve decision confidence\n\n"
        "## hard_constraints\n"
        "- budget and time horizon must be explicit\n"
        "- decision must remain reversible for pilot window\n\n"
        "## risk_signals\n"
        "- unresolved assumptions in layers/viewpoints\n"
        "- evidence gaps before selection stage\n\n"
        "## weakest_link\n"
        f"- {weak_hint}\n\n"
        "## anti_goodhart_risks\n"
        "- metric gaming by optimizing volume without value outcome\n"
        "- local KPI improvement with global system degradation\n\n"
        "## source_summary\n"
        f"- viewpoints: {viewpoint_summary[:180]}\n"
        f"- layers: {layer_summary[:180]}\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_indicator_set(payload: Dict[str, Any]) -> str:
    passport = str(payload.get("characterization_passport", "")).lower()
    indicators = [
        ("decision_confidence_score", "optimization_goal"),
        ("unresolved_critical_gaps", "hard_constraint"),
        ("stakeholder_alignment_risk", "risk_signal"),
    ]
    if "cash" in passport or "burn" in passport:
        indicators.append(("cash_burn_rate", "hard_constraint"))
    lines = ["# Indicator Set", ""]
    for name, role in indicators:
        lines.append(f"- {name} | role={role}")
    lines.extend(["", "_Generated by local-llm mode._"])
    return "\n".join(lines)


def _local_build_parity_plan(payload: Dict[str, Any]) -> str:
    indicator_set = str(payload.get("indicator_set", ""))
    indicators = []
    for ln in indicator_set.splitlines():
        s = ln.strip()
        if s.startswith("- "):
            indicators.append(s[2:].split("|")[0].strip())
    if not indicators:
        indicators = ["decision_confidence_score", "unresolved_critical_gaps"]

    lines = [
        "# Parity Plan",
        "",
        "## assumptions",
        "- all alternatives compared under same budget/time window",
        "- same baseline and source dataset",
        "",
        "## evaluation_window",
        "- 30 days",
        "",
        "## indicators_in_scope",
    ]
    lines.extend(f"- {x}" for x in indicators)
    lines.extend(["", "_Generated by local-llm mode._"])
    return "\n".join(lines)


def _local_build_characteristic_card(payload: Dict[str, Any]) -> str:
    indicator = str(payload.get("indicator", "generic_indicator"))
    role = str(payload.get("role", "risk_signal"))
    direction = "higher is better" if role == "optimization_goal" else "lower is better"
    return (
        f"# Characteristic Card: {indicator}\n\n"
        f"- role: {role}\n"
        f"- measurement: define clear counting rule for {indicator}\n"
        f"- direction: {direction}\n"
        "- valid_until: 2026-12-31\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_problem_bundle(payload: Dict[str, Any]) -> str:
    mode = str(payload.get("problem_output", "archive"))
    base_candidates = [
        {
            "id": "prob_01",
            "title": "Strategic-model mismatch",
            "severity": 5,
            "urgency": 5,
            "cost_of_inaction": "high",
            "complexity": 3,
            "owner": "strategy_owner",
        },
        {
            "id": "prob_02",
            "title": "Evidence debt before solution selection",
            "severity": 4,
            "urgency": 4,
            "cost_of_inaction": "medium",
            "complexity": 2,
            "owner": "analysis_owner",
        },
        {
            "id": "prob_03",
            "title": "Role ownership ambiguity",
            "severity": 3,
            "urgency": 4,
            "cost_of_inaction": "medium",
            "complexity": 2,
            "owner": "operations_owner",
        },
    ]

    for p in base_candidates:
        p["goldilocks_score"] = p["severity"] + p["urgency"] - p["complexity"]

    ranked = sorted(base_candidates, key=lambda x: x["goldilocks_score"], reverse=True)
    top = ranked[0]

    if mode == "archive":
        lines = ["# Problem Archive", ""]
        for p in ranked:
            lines.extend(
                [
                    f"## {p['id']} - {p['title']}",
                    f"- severity: {p['severity']}",
                    f"- urgency: {p['urgency']}",
                    f"- cost_of_inaction: {p['cost_of_inaction']}",
                    f"- owner: {p['owner']}",
                    f"- goldilocks_score: {p['goldilocks_score']}",
                    "",
                ]
            )
        lines.append("_Generated by local-llm mode._")
        return "\n".join(lines)

    if mode == "portfolio":
        lines = ["# Problem Portfolio", "", "Selected for current cycle:"]
        for p in ranked[:2]:
            lines.extend(
                [
                    f"- {p['id']} | {p['title']} | priority={p['goldilocks_score']} | owner={p['owner']}",
                ]
            )
        lines.extend(["", "_Generated by local-llm mode._"])
        return "\n".join(lines)

    if mode == "selected_card":
        return (
            "# Selected Problem Card\n\n"
            f"- problem_id: {top['id']}\n"
            f"- title: {top['title']}\n"
            "- symptoms:\n"
            "  - strategy and execution are misaligned\n"
            "  - decisions are made with unresolved evidence gaps\n"
            "- suspected_causes:\n"
            "  - missing explicit acceptance constraints\n"
            "  - unclear ownership model\n"
            "- affected_layers: business_model, requirements, allocation\n"
            "- affected_viewpoints: strategist, analyst, architect\n"
            "- evidence_refs: viewpoints/conflicts_index.md:L1\n"
            "- severity: high\n"
            "- urgency: high\n"
            "- cost_of_inaction: high\n"
            "- owner: strategy_owner\n"
            "- epistemic_status: inferred\n\n"
            "_Generated by local-llm mode._"
        )

    # acceptance spec
    return (
        "# Comparison & Acceptance Spec\n\n"
        "## indicators\n"
        "- decision_confidence_score >= 0.7\n"
        "- unresolved_critical_gaps <= 1\n\n"
        "## hard_constraints\n"
        "- budget_limit: fixed\n"
        "- time_horizon_days: 30\n\n"
        "## selection_policy\n"
        "- choose option that satisfies constraints and maximizes confidence gain\n"
        "- reject options violating hard constraints\n\n"
        "## reversibility\n"
        "- change must be reversible within pilot window\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_solution_portfolio(payload: Dict[str, Any]) -> str:
    return (
        "# Solution Portfolio\n\n"
        "## sol_00_status_quo\n"
        "- type: baseline\n"
        "- assurance_level: low\n"
        "- solves_which_problems: partial\n"
        "- assumptions: no change\n"
        "- expected_effects: low\n"
        "- risks: continued degradation\n"
        "- constraints: none\n"
        "- required_capabilities: existing only\n"
        "- reversibility: n/a\n"
        "- affected_viewpoints: strategist, operator, analyst\n"
        "- evidence_refs: problems/SelectedProblemCard.md:L1\n\n"
        "## sol_01_process_rewire\n"
        "- type: process\n"
        "- assurance_level: medium\n"
        "- solves_which_problems: strong\n"
        "- assumptions: governance alignment\n"
        "- expected_effects: medium-high\n"
        "- risks: adoption friction\n"
        "- constraints: time window 30 days\n"
        "- required_capabilities: ops lead + analytics\n"
        "- reversibility: medium\n"
        "- affected_viewpoints: operator, analyst\n"
        "- evidence_refs: problems/ComparisonAcceptanceSpec.md:L1\n\n"
        "## sol_02_architecture_slice\n"
        "- type: architecture\n"
        "- assurance_level: medium\n"
        "- solves_which_problems: high\n"
        "- assumptions: feasible modular rollout\n"
        "- expected_effects: high\n"
        "- risks: integration complexity\n"
        "- constraints: budget cap\n"
        "- required_capabilities: architect + delivery team\n"
        "- reversibility: medium-high\n"
        "- affected_viewpoints: architect, strategist\n"
        "- evidence_refs: problems/ComparisonAcceptanceSpec.md:L1\n\n"
        "## sol_03_policy_reset\n"
        "- type: governance\n"
        "- assurance_level: medium\n"
        "- solves_which_problems: medium\n"
        "- assumptions: executive support\n"
        "- expected_effects: medium\n"
        "- risks: stakeholder pushback\n"
        "- constraints: coordination overhead\n"
        "- required_capabilities: leadership + PMO\n"
        "- reversibility: medium\n"
        "- affected_viewpoints: strategist, client, critic\n"
        "- evidence_refs: viewpoints/conflicts_index.md:L1\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_parity_tradeoff(payload: Dict[str, Any]) -> str:
    mode = str(payload.get("solution_output", "parity_report"))
    if mode == "parity_plan":
        return (
            "# Parity Plan\n\n"
            "- comparison frame: same budget, same 30-day window, same baseline\n"
            "- criteria: confidence_gain, unresolved_gaps, risk_exposure, reversibility\n"
            "- unknown handling: unknown counted as penalty\n\n"
            "_Generated by local-llm mode._"
        )

    if mode == "tradeoff_table":
        return (
            "# Tradeoff Table\n\n"
            "| solution | confidence_gain | unresolved_gaps | risk_exposure | reversibility |\n"
            "|---|---|---|---|---|\n"
            "| sol_00_status_quo | low | high | high | n/a |\n"
            "| sol_01_process_rewire | medium | medium | medium | medium |\n"
            "| sol_02_architecture_slice | high | low | medium | medium-high |\n"
            "| sol_03_policy_reset | medium | medium | medium-high | medium |\n\n"
            "_Generated by local-llm mode._"
        )

    return (
        "# Parity Report\n\n"
        "- sol_02_architecture_slice dominates sol_00_status_quo on target criteria.\n"
        "- sol_01_process_rewire and sol_03_policy_reset remain viable with different tradeoffs.\n"
        "- parity validity: usable with minor unknown penalties.\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_conflict_routing(payload: Dict[str, Any]) -> str:
    return (
        "# Conflict Records\n\n"
        "## conflict_01\n"
        "- conflict_type: quality-attribute conflict\n"
        "- layers_involved: requirements,functional\n"
        "- viewpoints_involved: analyst,architect\n"
        "- method_selected: ATAM\n"
        "- selection_rationale: tradeoff between speed and reliability\n"
        "- resolution_status: resolved\n\n"
        "## conflict_02\n"
        "- conflict_type: alternative ranking conflict\n"
        "- layers_involved: business_model,allocation\n"
        "- viewpoints_involved: strategist,operator,client\n"
        "- method_selected: MCDA\n"
        "- selection_rationale: need explicit weighted comparison\n"
        "- resolution_status: resolved\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_selection_bundle(payload: Dict[str, Any]) -> str:
    mode = str(payload.get("solution_output", "selected_solutions"))
    if mode == "selected_solutions":
        return (
            "# Selected Solutions\n\n"
            "- sol_02_architecture_slice\n"
            "- sol_01_process_rewire\n\n"
            "Rejected:\n"
            "- sol_00_status_quo (fails acceptance constraints)\n"
            "- sol_03_policy_reset (higher risk exposure under current horizon)\n\n"
            "_Generated by local-llm mode._"
        )
    if mode == "adr":
        return (
            "# ADR-001: Solution Selection\n\n"
            "## Context\n"
            "- Selection based on ComparisonAcceptanceSpec and parity/conflict outputs.\n\n"
            "## Decision\n"
            "- Choose sol_02_architecture_slice as primary and sol_01_process_rewire as support.\n\n"
            "## Rejected Alternatives\n"
            "- sol_00_status_quo: does not satisfy constraints.\n"
            "- sol_03_policy_reset: weaker parity score.\n\n"
            "## Risks\n"
            "- integration complexity; adoption lag.\n\n"
            "## Evidence Basis\n"
            "- problems/ComparisonAcceptanceSpec.md:L1\n"
            "- solutions/ParityReport.md:L1\n"
            "- solutions/ConflictRecords.md:L1\n\n"
            "_Generated by local-llm mode._"
        )
    if mode == "runbook":
        return (
            "# Runbook\n\n"
            "1. Align owners and success criteria.\n"
            "2. Launch limited architecture slice.\n"
            "3. Measure indicators weekly.\n"
            "4. Expand only if acceptance thresholds are stable.\n\n"
            "_Generated by local-llm mode._"
        )
    return (
        "# Rollback Plan\n\n"
        "- Trigger rollback if unresolved_critical_gaps increases for 2 consecutive checks.\n"
        "- Revert to previous baseline process and freeze expansion.\n"
        "- Re-open problem framing with updated evidence.\n\n"
        "_Generated by local-llm mode._"
    )


def _short_lines(text: str, max_lines: int = 4) -> List[str]:
    lines: List[str] = []
    for raw in str(text).splitlines():
        s = raw.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("- "):
            s = s[2:].strip()
        if len(s) < 3:
            continue
        lines.append(s)
    return lines[:max_lines]


def _local_build_reporting_analytical(payload: Dict[str, Any]) -> str:
    sections = payload.get("analytical_sections", [])
    artifacts = payload.get("artifact_context", {})
    missing = set(payload.get("missing_sources", []))

    parts = ["# Аналитический полный отчет", ""]
    for section in sections:
        idx = str(section.get("index", ""))
        title = str(section.get("title", ""))
        rel = str(section.get("source", ""))
        text = str(artifacts.get(rel, ""))

        if not text or rel in missing:
            body = (
                "- Что зафиксировано: GAP: source artifact missing or empty.\n"
                "- Почему это важно: без этого источника отчет теряет часть доказательной основы и управленческой надежности.\n"
                f"- Что сделать: восстановить `{rel}`, затем повторить сборку отчета."
            )
        else:
            lines = _short_lines(text, max_lines=6)
            observed = "; ".join(lines[:2]) if lines else "факты описаны частично"
            because = "; ".join(lines[2:4]) if len(lines) > 2 else "дополнительные ограничения не раскрыты полностью"
            therefore = "; ".join(lines[4:6]) if len(lines) > 4 else "нужна синхронизация решений, критериев приемки и плана внедрения"
            body = (
                f"- Что происходит: {observed}.\n"
                f"- Почему это важно: {because}.\n"
                f"- К чему это ведет и что делать: {therefore}."
            )

        parts.extend([f"## {idx}. {title}", f"- source: {rel}", body, ""])

    parts.extend(
        [
            "## Traceability",
            "- Выводы сформированы только на базе входных артефактов кейса без добавления новых фактов.",
            "- Для каждого раздела сохраняется ссылка на исходный артефакт.",
            "",
            "_Generated by local-llm mode._",
        ]
    )
    return "\n".join(parts)


def _local_build_reporting_executive(payload: Dict[str, Any]) -> str:
    sections = payload.get("executive_sections", [])
    artifacts = payload.get("artifact_context", {})
    selected = str(artifacts.get("solutions/SelectedSolutions.md", ""))
    selected_lines = [ln.strip()[2:] for ln in selected.splitlines() if ln.strip().startswith("- ")][:3]

    recommendations = (
        "\n".join(f"- {item}: решение взято в работу как управляемый вариант под текущие ограничения." for item in selected_lines)
        if selected_lines
        else "- GAP: рекомендации не опубликованы, так как не зафиксирован evidence status."
    )
    default_sections = {
        "1": "Кейс находится в точке, где нужно одновременно удержать темп реализации и снизить риск неверного стратегического выбора.",
        "2": "Ключевая проблема — рассогласование между целевой логикой проекта и фактической организацией исполнения.",
        "3": "Главный конфликт интересов проходит между потребностью в быстрых изменениях и требованиями к устойчивости результата.",
        "4": recommendations,
        "5": "Выбранный вариант лучше проходит ограничения текущего цикла, хотя требует строгой дисциплины внедрения и контроля.",
        "6": "Сохраняются риски по полноте доказательной базы, согласованности ролей и реалистичности темпа внедрения.",
        "7": "Откат активируется при ухудшении ключевых метрик в двух последовательных контрольных периодах.",
        "8": "Следующий шаг — ограниченный пилот с назначенным владельцем, сроком и измеримыми критериями результата.",
        "9": "Контроль фокусируется на уверенности решения, числе критических пробелов и динамике организационных рисков.",
        "10": "Уровень уверенности рабочий для пилота, но не финальный для масштабирования без дополнительной проверки.",
    }

    parts = ["# Краткая управленческая записка", ""]
    for section in sections:
        idx = str(section.get("index", ""))
        title = str(section.get("title", ""))
        parts.extend([f"## {idx}. {title}", default_sections.get(idx, "Раздел ожидает уточнения по артефактам."), ""])
    parts.append("_Generated by local-llm mode._")
    return "\n".join(parts)


def _call_openai_responses(system_prompt: str, user_payload: Dict[str, Any]) -> str:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set")

    model = os.environ.get("OPENAI_MODEL", "gpt-4.1-mini")
    req_payload = {
        "model": model,
        "input": [
            {"role": "system", "content": [{"type": "input_text", "text": system_prompt}]},
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": json.dumps(user_payload, ensure_ascii=False),
                    }
                ],
            },
        ],
    }

    request = urllib.request.Request(
        "https://api.openai.com/v1/responses",
        data=json.dumps(req_payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    with urllib.request.urlopen(request, timeout=60) as resp:
        raw = json.loads(resp.read().decode("utf-8"))

    text = raw.get("output_text", "")
    if text:
        return text

    output = raw.get("output", [])
    if output and isinstance(output, list):
        for item in output:
            content = item.get("content", [])
            for block in content:
                txt = block.get("text")
                if txt:
                    return txt
    return ""


def _call_antigravity_adapter(system_prompt: str, user_payload: Dict[str, Any]) -> str:
    """
    Optional adapter for Antigravity-managed LLMs.
    Expects env ANTIGRAVITY_LLM_CMD with a shell command that reads JSON from stdin
    and returns markdown text to stdout.
    """
    cmd = os.environ.get("ANTIGRAVITY_LLM_CMD", "").strip()
    if not cmd:
        return ""

    req = {
        "system_prompt": system_prompt,
        "user_payload": user_payload,
    }
    proc = subprocess.run(
        cmd,
        input=json.dumps(req, ensure_ascii=False),
        text=True,
        shell=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        return ""
    return (proc.stdout or "").strip()


def _call_gemini_responses(system_prompt: str, user_payload: Dict[str, Any]) -> str:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY is not set")

    model = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash")
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
    
    req_payload = {
        "systemInstruction": {
            "parts": [{"text": system_prompt}]
        },
        "contents": [
            {
                "parts": [{"text": json.dumps(user_payload, ensure_ascii=False)}]
            }
        ],
        "generationConfig": {
            "temperature": 0.2
        }
    }

    request = urllib.request.Request(
        url,
        data=json.dumps(req_payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    max_retries = 5
    for attempt in range(max_retries):
        try:
            with urllib.request.urlopen(request, timeout=180) as resp:
                raw = json.loads(resp.read().decode("utf-8"))
            
            candidates = raw.get("candidates", [])
            if candidates:
                content = candidates[0].get("content", {})
                parts = content.get("parts", [])
                if parts:
                    return parts[0].get("text", "")
            return ""
            
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8", errors="ignore")
            if e.code in (429, 503):
                if attempt == 0:
                    print(f"  [API] Детали ошибки {e.code} от Google: {error_body.strip()[:200]}")
                wait_time = (attempt + 1) * 15  # 15s, 30s, 45s...
                print(f"  [API] Временно уперлись в лимит или сервер перегружен (Error {e.code}). Ждем {wait_time} сек... (Попытка {attempt+1}/{max_retries})")
                time.sleep(wait_time)
                continue
            else:
                print(f"Gemini API HTTP Error: {e.code} - {e.reason}\nBody: {error_body}")
                break
        except Exception as e:
            print(f"Gemini API error: {e}")
            if attempt < max_retries - 1:
                wait_time = (attempt + 1) * 15
                print(f"  [API] Сетевая ошибка или таймаут. Ждем {wait_time} сек... (Попытка {attempt+1}/{max_retries})")
                time.sleep(wait_time)
                continue
            break
        
    return ""


def generate_markdown_with_skill(
    system_skill_prompt: str,
    user_payload: Dict[str, Any],
    mode: str = "local",
) -> str:
    selected = (mode or "local").lower()
    task_type = str(user_payload.get("task_type", ""))

    if selected == "antigravity":
        text = _call_antigravity_adapter(system_skill_prompt, user_payload)
        if text.strip():
            return text

    if selected == "openai":
        text = _call_openai_responses(system_skill_prompt, user_payload)
        if text.strip():
            return text

    if selected == "gemini":
        text = _call_gemini_responses(system_skill_prompt, user_payload)
        if text.strip():
            return text

    if task_type == "build_layer":
        return _local_build_layer(user_payload)
    if task_type == "build_viewpoint":
        return _local_build_viewpoint(user_payload)
    if task_type == "build_characterization":
        return _local_build_characterization(user_payload)
    if task_type == "build_indicator_set":
        return _local_build_indicator_set(user_payload)
    if task_type == "build_parity_plan":
        return _local_build_parity_plan(user_payload)
    if task_type == "build_characteristic_card":
        return _local_build_characteristic_card(user_payload)
    if task_type == "build_problem_bundle":
        return _local_build_problem_bundle(user_payload)
    if task_type == "build_solution_portfolio":
        return _local_build_solution_portfolio(user_payload)
    if task_type == "build_parity_tradeoff":
        return _local_build_parity_tradeoff(user_payload)
    if task_type == "build_conflict_routing":
        return _local_build_conflict_routing(user_payload)
    if task_type == "build_selection_bundle":
        return _local_build_selection_bundle(user_payload)
    if task_type == "build_reporting_analytical":
        return _local_build_reporting_analytical(user_payload)
    if task_type == "build_reporting_executive":
        return _local_build_reporting_executive(user_payload)

    return "# Generated Artifact\n\n- No task-specific local renderer configured.\n\n_Generated by local-llm mode._"
