from __future__ import annotations

import json
import os
import re
import subprocess
import time
import urllib.error
import urllib.request
from typing import Any, Dict, List


def _extract_lines(text: str) -> List[str]:
    return [ln.strip() for ln in text.splitlines() if ln.strip() and not ln.strip().startswith("#")]


def _contains_any(text: str, keywords: List[str]) -> bool:
    low = text.lower()
    return any(k in low for k in keywords)


def _local_build_layer(payload: Dict[str, Any]) -> str:
    layer = payload.get("layer_name", "layer")
    normalized_case = str(payload.get("normalized_case", ""))
    lines = _extract_lines(normalized_case)
    joined = " ".join(lines).lower()

    def pick(keys: List[str], fallback: str) -> List[str]:
        picked = [ln for ln in lines if any(k in ln.lower() for k in keys)]
        return picked[:8] if picked else [fallback]

    if layer == "layer_1_business_model":
        points = pick(["value", "client", "market", "strategy", "цінн", "рин", "клієн", "конкур"], "GAP: business context is weak")
        title = "# Layer 1: Business Model"
        if _contains_any(joined, ["technical director", "технічний директор", "тд"]) and _contains_any(joined, ["7-10", "7–10", "delay", "затрим"]):
            points = [
                "Business model depends on fast response to incoming requests, but pricing is bottlenecked on a single expert.",
                "Client value is degraded by 7-10 day quoting delay, which pushes deals to faster competitors.",
                "High-cost engineering time is consumed before deal qualification, creating hidden acquisition cost.",
                "The company behaves like custom R&D while the intake stream contains a large share of repeatable requests.",
            ]
    elif layer == "layer_2_requirements":
        points = pick(["must", "should", "need", "require", "треб", "повин", "необхід"], "GAP: requirements not explicit")
        title = "# Layer 2: Requirements"
        if _contains_any(joined, ["technical director", "технічний директор", "тд"]):
            points = [
                "The process must reduce dependence on the Technical Director for routine quotation work.",
                "Quoting turnaround should move from multi-day delay to an operationally safe near-real-time window.",
                "Any delegation must preserve pricing accuracy and protect production commitments.",
                "The workflow needs explicit qualification gates before escalation into deep technical review.",
            ]
    elif layer == "layer_3_functional_model":
        points = pick(["process", "flow", "stage", "function", "процес", "етап", "вироб"], "GAP: functional flow unclear")
        title = "# Layer 3: Functional Model"
        if _contains_any(joined, ["technical director", "технічний директор", "тд"]):
            points = [
                "Current flow is linear: lead intake -> manager handoff -> Technical Director estimation -> client response.",
                "There is no triage stage separating standard requests from non-standard engineering work.",
                "The same functional path serves both low-value and high-complexity requests, creating queue accumulation.",
                "Production control and presales estimation are coupled inside one overloaded function.",
            ]
    else:
        points = pick(["role", "owner", "team", "manager", "правл", "команд", "роль"], "GAP: allocation ownership undefined")
        title = "# Layer 4: Allocation Model"
        if _contains_any(joined, ["technical director", "технічний директор", "тд"]):
            points = [
                "Sales Manager currently acts as a courier rather than an accountable qualifier of demand.",
                "Technical Director combines incompatible roles: production owner, engineering reviewer, and price calculator.",
                "No dedicated L1 estimator or routing owner exists for standard cases.",
                "Responsibility for speed sits in sales while responsibility for accuracy sits in production, creating structural conflict.",
            ]

    return title + "\n\n" + "\n".join(f"- {x}" for x in points) + "\n\n_Generated by local-llm mode._"


def _local_build_viewpoint(payload: Dict[str, Any]) -> str:
    viewpoint = str(payload.get("viewpoint", "viewpoint"))
    focus = str(payload.get("focus", ""))
    layers = payload.get("layers", {})

    def first_line(key: str) -> str:
        txt = str(layers.get(key, ""))
        lines = _extract_lines(txt)
        return lines[0] if lines else "no data"

    l1 = first_line("layer_1")
    l2 = first_line("layer_2")
    l3 = first_line("layer_3")
    l4 = first_line("layer_4")

    gaps = []
    for k, v in layers.items():
        if "GAP:" in str(v):
            gaps.append(f"{k} has unresolved GAP")

    objections = [f"Potential risk from {viewpoint} perspective"]
    if gaps:
        objections.append("Unresolved GAPs reduce decision confidence")

    body = [
        f"# Viewpoint: {viewpoint}",
        "",
        "## viewpoint_name",
        viewpoint,
        "",
        "## primary_concerns",
        f"- {focus}",
        "- preserve traceability and evidence quality",
        "",
        "## layer_findings",
        f"- layer_1: {l1}",
        f"- layer_2: {l2}",
        f"- layer_3: {l3}",
        f"- layer_4: {l4}",
        "",
        "## key_risks",
        "- decision under incomplete data",
        "- cross-layer inconsistency",
        "",
        "## supported_actions",
        "- proceed with explicit assumptions register",
        "",
        "## objections",
        *[f"- {x}" for x in objections],
        "",
        "## evidence_gaps",
        *( [f"- {g}" for g in gaps] if gaps else ["- none"] ),
        "",
        "## non_negotiables",
        "- do not skip acceptance constraints",
        "- keep links to source evidence",
        "",
        "_Generated by local-llm mode._",
    ]
    return "\n".join(body)


def _local_build_characterization(payload: Dict[str, Any]) -> str:
    viewpoint_summary = str(payload.get("viewpoint_summary", ""))
    layer_summary = str(payload.get("layer_summary", ""))
    weak_hint = "investment_status" if "invest" in viewpoint_summary.lower() else "team_alignment"
    return (
        "# Characterization Passport\n\n"
        "## optimization_goals\n"
        "- reduce strategic uncertainty and improve decision confidence\n\n"
        "## hard_constraints\n"
        "- budget and time horizon must be explicit\n"
        "- decision must remain reversible for pilot window\n\n"
        "## risk_signals\n"
        "- unresolved assumptions in layers/viewpoints\n"
        "- evidence gaps before selection stage\n\n"
        "## weakest_link\n"
        f"- {weak_hint}\n\n"
        "## anti_goodhart_risks\n"
        "- metric gaming by optimizing volume without value outcome\n"
        "- local KPI improvement with global system degradation\n\n"
        "## source_summary\n"
        f"- viewpoints: {viewpoint_summary[:180]}\n"
        f"- layers: {layer_summary[:180]}\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_indicator_set(payload: Dict[str, Any]) -> str:
    passport = str(payload.get("characterization_passport", "")).lower()
    indicators = [
        ("decision_confidence_score", "optimization_goal"),
        ("unresolved_critical_gaps", "hard_constraint"),
        ("stakeholder_alignment_risk", "risk_signal"),
    ]
    if "cash" in passport or "burn" in passport:
        indicators.append(("cash_burn_rate", "hard_constraint"))
    lines = ["# Indicator Set", ""]
    for name, role in indicators:
        lines.append(f"- {name} | role={role}")
    lines.extend(["", "_Generated by local-llm mode._"])
    return "\n".join(lines)


def _local_build_parity_plan(payload: Dict[str, Any]) -> str:
    indicator_set = str(payload.get("indicator_set", ""))
    indicators = []
    for ln in indicator_set.splitlines():
        s = ln.strip()
        if s.startswith("- "):
            indicators.append(s[2:].split("|")[0].strip())
    if not indicators:
        indicators = ["decision_confidence_score", "unresolved_critical_gaps"]

    lines = [
        "# Parity Plan",
        "",
        "## assumptions",
        "- all alternatives compared under same budget/time window",
        "- same baseline and source dataset",
        "",
        "## evaluation_window",
        "- 30 days",
        "",
        "## indicators_in_scope",
    ]
    lines.extend(f"- {x}" for x in indicators)
    lines.extend(["", "_Generated by local-llm mode._"])
    return "\n".join(lines)


def _local_build_characteristic_card(payload: Dict[str, Any]) -> str:
    indicator = str(payload.get("indicator", "generic_indicator"))
    role = str(payload.get("role", "risk_signal"))
    direction = "higher is better" if role == "optimization_goal" else "lower is better"
    return (
        f"# Characteristic Card: {indicator}\n\n"
        f"- role: {role}\n"
        f"- measurement: define clear counting rule for {indicator}\n"
        f"- direction: {direction}\n"
        "- valid_until: 2026-12-31\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_problem_bundle(payload: Dict[str, Any]) -> str:
    mode = str(payload.get("problem_output", "archive"))
    passport = str(payload.get("characterization_passport", ""))
    indicators = str(payload.get("indicator_set", ""))
    case_hint = (passport + "\n" + indicators).lower()
    if _contains_any(case_hint, ["technical director", "технического директора", "технічного директора", "triage", "routing", "quote"]):
        base_candidates = [
            {
                "id": "prob_01",
                "title": "Technical Director quotation bottleneck",
                "severity": 5,
                "urgency": 5,
                "cost_of_inaction": "high",
                "complexity": 2,
                "owner": "operations_owner",
            },
            {
                "id": "prob_02",
                "title": "Unqualified leads escalate into expert workflow",
                "severity": 4,
                "urgency": 5,
                "cost_of_inaction": "high",
                "complexity": 2,
                "owner": "sales_owner",
            },
            {
                "id": "prob_03",
                "title": "Knowledge is not externalized into repeatable estimation tools",
                "severity": 4,
                "urgency": 4,
                "cost_of_inaction": "medium",
                "complexity": 3,
                "owner": "strategy_owner",
            },
        ]
    else:
        base_candidates = [
            {
                "id": "prob_01",
                "title": "Strategic-model mismatch",
                "severity": 5,
                "urgency": 5,
                "cost_of_inaction": "high",
                "complexity": 3,
                "owner": "strategy_owner",
            },
            {
                "id": "prob_02",
                "title": "Evidence debt before solution selection",
                "severity": 4,
                "urgency": 4,
                "cost_of_inaction": "medium",
                "complexity": 2,
                "owner": "analysis_owner",
            },
            {
                "id": "prob_03",
                "title": "Role ownership ambiguity",
                "severity": 3,
                "urgency": 4,
                "cost_of_inaction": "medium",
                "complexity": 2,
                "owner": "operations_owner",
            },
        ]

    for p in base_candidates:
        p["goldilocks_score"] = p["severity"] + p["urgency"] - p["complexity"]

    ranked = sorted(base_candidates, key=lambda x: x["goldilocks_score"], reverse=True)
    top = ranked[0]

    def _facts_block(items: List[str]) -> str:
        return "\n".join(f"- {item}" for item in items)

    if mode == "archive":
        lines = ["# Problem Archive", ""]
        for p in ranked:
            lines.extend(
                [
                    f"## {p['id']} - {p['title']}",
                    "### Facts",
                    f"- severity signal: {p['severity']}",
                    f"- urgency signal: {p['urgency']}",
                    "### Interpretations",
                    f"- the problem is material enough to enter the current cycle with owner {p['owner']}",
                    "### Hypotheses to Validate",
                    "- the described severity and urgency are stable after quantitative clarification",
                    f"- severity: {p['severity']}",
                    f"- urgency: {p['urgency']}",
                    f"- cost_of_inaction: {p['cost_of_inaction']}",
                    f"- owner: {p['owner']}",
                    f"- goldilocks_score: {p['goldilocks_score']}",
                    "",
                ]
            )
        lines.append("_Generated by local-llm mode._")
        return "\n".join(lines)

    if mode == "portfolio":
        lines = ["# Problem Portfolio", "", "## Facts", "", "Selected for current cycle:"]
        for p in ranked[:2]:
            lines.extend(
                [
                    f"- {p['id']} | {p['title']} | priority={p['goldilocks_score']} | owner={p['owner']}",
                ]
            )
        lines.extend(
            [
                "",
                "## Interpretations",
                "",
                "- The portfolio keeps only problems that are both significant and bounded for the current cycle.",
                "",
                "## Hypotheses to Validate",
                "",
                "- Priority order may change after quantitative clarification of throughput, economics, and failure rate.",
                "",
                "_Generated by local-llm mode._",
            ]
        )
        return "\n".join(lines)

    if mode == "selected_card":
        if "Technical Director quotation bottleneck" in top["title"]:
            return (
                "# Selected Problem Card\n\n"
                f"- problem_id: {top['id']}\n"
                "- title: Decouple standard quotation work from the Technical Director\n"
                "## Facts\n"
                "- 100% of incoming requests are routed to one overloaded expert\n"
                "- quote turnaround stretches to multi-day delay\n"
                "- production attention is fragmented by presales work\n"
                "## Interpretations\n"
                "- the current flow concentrates routine and non-routine estimation in one expert bottleneck\n"
                "- the process lacks a reusable mechanism for standard quotation work\n"
                "## Hypotheses to Validate\n"
                "- the largest share of delay comes from absent triage before technical escalation\n"
                "- part of the pricing logic can be externalized without unacceptable accuracy loss\n"
                "- affected_layers: business_model, functional_model, allocation\n"
                "- affected_viewpoints: strategist, operator, architect, client\n"
                "- evidence_refs: viewpoints/conflicts_index.md:L1\n"
                "- severity: high\n"
                "- urgency: high\n"
                "- cost_of_inaction: high\n"
                f"- owner: {top['owner']}\n"
                "- epistemic_status: observed\n\n"
                "_Generated by local-llm mode._"
            )
        return (
            "# Selected Problem Card\n\n"
            f"- problem_id: {top['id']}\n"
            f"- title: {top['title']}\n"
            "## Facts\n"
            "- strategy and execution are misaligned\n"
            "- decisions are made with unresolved evidence gaps\n"
            "## Interpretations\n"
            "- the project lacks a stable decision frame that connects strategy, execution, and ownership\n"
            "## Hypotheses to Validate\n"
            "- missing explicit acceptance constraints are the main driver of decision drift\n"
            "- ownership clarification will materially reduce rework and ambiguity\n"
            "- affected_layers: business_model, requirements, allocation\n"
            "- affected_viewpoints: strategist, analyst, architect\n"
            "- evidence_refs: viewpoints/conflicts_index.md:L1\n"
            "- severity: high\n"
            "- urgency: high\n"
            "- cost_of_inaction: high\n"
            "- owner: strategy_owner\n"
            "- epistemic_status: inferred\n\n"
            "_Generated by local-llm mode._"
        )

    # acceptance spec
    if "Technical Director quotation bottleneck" in top["title"]:
        return (
            "# Comparison & Acceptance Spec\n\n"
            "## indicators\n"
            "- quote_turnaround_hours <= 24 for standard requests\n"
            "- triage_rate >= 0.8\n"
            "- production_sla_adherence >= 0.95\n\n"
            "## hard_constraints\n"
            "- quote_accuracy_delta_pct <= 5\n"
            "- no production disruption during pilot window\n"
            "- operating cost of the new flow must not exceed current hidden expert cost\n\n"
            "## selection_policy\n"
            "- prefer reversible solutions that externalize pricing logic before delegation\n"
            "- reject options that improve speed by sacrificing margin control\n\n"
            "## reversibility\n"
            "- routing authority can be returned to the Technical Director within one control cycle\n\n"
            "_Generated by local-llm mode._"
        )
    return (
        "# Comparison & Acceptance Spec\n\n"
        "## indicators\n"
        "- decision_confidence_score >= 0.7\n"
        "- unresolved_critical_gaps <= 1\n\n"
        "## hard_constraints\n"
        "- budget_limit: fixed\n"
        "- time_horizon_days: 30\n\n"
        "## selection_policy\n"
        "- choose option that satisfies constraints and maximizes confidence gain\n"
        "- reject options violating hard constraints\n\n"
        "## reversibility\n"
        "- change must be reversible within pilot window\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_solution_portfolio(payload: Dict[str, Any]) -> str:
    selected_problem = str(payload.get("selected_problem_card", "")).lower()
    if _contains_any(selected_problem, ["technical director", "технического директора", "технічного директора"]):
        return (
            "# Solution Portfolio\n\n"
            "## sol_00_status_quo\n"
            "- type: baseline\n"
            "- assurance_level: low\n"
            "- anti_goodhart_risk: hidden cost stays invisible because no one changes the metric frame\n"
            "- solves_which_problems: none\n"
            "- assumptions: keep all quotations on the Technical Director\n"
            "- expected_effects: preserves current bottleneck and hidden cost\n"
            "- risks: continued queue growth, client loss, production distraction\n"
            "- constraints: no structural change\n"
            "- required_capabilities: existing only\n"
            "- reversibility: n/a\n"
            "- affected_viewpoints: strategist, operator, analyst\n"
            "- evidence_refs: problems/SelectedProblemCard.md:L1\n\n"
            "## sol_01_shadow_mode_matrix\n"
            "- type: process\n"
            "- assurance_level: high\n"
            "- anti_goodhart_risk: team may optimize matrix match score while ignoring real downstream profitability\n"
            "- solves_which_problems: strong\n"
            "- assumptions: expert knowledge can be partially externalized\n"
            "- expected_effects: safer learning path toward faster quotation\n"
            "- risks: slow initial effect and possible expert resistance\n"
            "- constraints: requires disciplined dual-run pilot\n"
            "- required_capabilities: analyst + Technical Director + sales lead\n"
            "- reversibility: high\n"
            "- affected_viewpoints: operator, analyst, critic\n"
            "- evidence_refs: problems/ComparisonAcceptanceSpec.md:L1\n\n"
            "## sol_02_l1_estimator_gate\n"
            "- type: process\n"
            "- assurance_level: medium\n"
            "- anti_goodhart_risk: managers may game qualification or force-fit complex work into standard categories for speed\n"
            "- solves_which_problems: high\n"
            "- assumptions: standard requests can be separated from custom engineering work\n"
            "- expected_effects: major reduction in response time and expert load\n"
            "- risks: misclassification and margin error if delegated too early\n"
            "- constraints: requires qualification gate and accuracy control\n"
            "- required_capabilities: sales ops + L1 estimator + governance owner\n"
            "- reversibility: medium-high\n"
            "- affected_viewpoints: operator, client, strategist\n"
            "- evidence_refs: problems/ComparisonAcceptanceSpec.md:L1\n\n"
            "## sol_03_client_cpq_portal\n"
            "- type: architecture\n"
            "- assurance_level: low\n"
            "- anti_goodhart_risk: portal may optimize throughput metrics while degrading deal quality and client fit\n"
            "- solves_which_problems: medium\n"
            "- assumptions: the request space is standardized enough for self-service\n"
            "- expected_effects: radical acceleration for standard requests\n"
            "- risks: high implementation cost and weak adoption fit\n"
            "- constraints: budget and integration burden\n"
            "- required_capabilities: architect + product owner + implementation team\n"
            "- reversibility: low\n"
            "- affected_viewpoints: architect, strategist, client\n"
            "- evidence_refs: problems/ComparisonAcceptanceSpec.md:L1\n\n"
            "_Generated by local-llm mode._"
        )
    return (
        "# Solution Portfolio\n\n"
        "## sol_00_status_quo\n"
        "- type: baseline\n"
        "- assurance_level: low\n"
        "- anti_goodhart_risk: hidden structural waste remains unmeasured under status quo\n"
        "- solves_which_problems: partial\n"
        "- assumptions: no change\n"
        "- expected_effects: low\n"
        "- risks: continued degradation\n"
        "- constraints: none\n"
        "- required_capabilities: existing only\n"
        "- reversibility: n/a\n"
        "- affected_viewpoints: strategist, operator, analyst\n"
        "- evidence_refs: problems/SelectedProblemCard.md:L1\n\n"
        "## sol_01_process_rewire\n"
        "- type: process\n"
        "- assurance_level: medium\n"
        "- anti_goodhart_risk: local process speed may improve while unresolved gaps are simply moved downstream\n"
        "- solves_which_problems: strong\n"
        "- assumptions: governance alignment\n"
        "- expected_effects: medium-high\n"
        "- risks: adoption friction\n"
        "- constraints: time window 30 days\n"
        "- required_capabilities: ops lead + analytics\n"
        "- reversibility: medium\n"
        "- affected_viewpoints: operator, analyst\n"
        "- evidence_refs: problems/ComparisonAcceptanceSpec.md:L1\n\n"
        "## sol_02_architecture_slice\n"
        "- type: architecture\n"
        "- assurance_level: medium\n"
        "- anti_goodhart_risk: delivery teams may optimize rollout velocity instead of stable outcome quality\n"
        "- solves_which_problems: high\n"
        "- assumptions: feasible modular rollout\n"
        "- expected_effects: high\n"
        "- risks: integration complexity\n"
        "- constraints: budget cap\n"
        "- required_capabilities: architect + delivery team\n"
        "- reversibility: medium-high\n"
        "- affected_viewpoints: architect, strategist\n"
        "- evidence_refs: problems/ComparisonAcceptanceSpec.md:L1\n\n"
        "## sol_03_policy_reset\n"
        "- type: policy\n"
        "- assurance_level: medium\n"
        "- anti_goodhart_risk: policy compliance can be gamed without improving actual operational behavior\n"
        "- solves_which_problems: medium\n"
        "- assumptions: executive support\n"
        "- expected_effects: medium\n"
        "- risks: stakeholder pushback\n"
        "- constraints: coordination overhead\n"
        "- required_capabilities: leadership + PMO\n"
        "- reversibility: medium\n"
        "- affected_viewpoints: strategist, client, critic\n"
        "- evidence_refs: viewpoints/conflicts_index.md:L1\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_parity_tradeoff(payload: Dict[str, Any]) -> str:
    mode = str(payload.get("solution_output", "parity_report"))
    portfolio = str(payload.get("solution_portfolio", "")).lower()
    td_case = _contains_any(portfolio, ["shadow_mode_matrix", "l1_estimator_gate", "client_cpq_portal"])
    if mode == "parity_plan":
        return (
            "# Parity Plan\n\n"
            "- comparison frame: same budget, same 30-day window, same baseline\n"
            "- criteria: confidence_gain, unresolved_gaps, risk_exposure, reversibility\n"
            "- unknown handling: unknown counted as penalty\n\n"
            "_Generated by local-llm mode._"
        )

    if mode == "tradeoff_table":
        return (
            "# Tradeoff Table\n\n"
            "| solution | confidence_gain | unresolved_gaps | risk_exposure | reversibility |\n"
            "|---|---|---|---|---|\n"
            "| sol_00_status_quo | low | high | high | n/a |\n"
            "| sol_01_process_rewire | medium | medium | medium | medium |\n"
            "| sol_02_architecture_slice | high | low | medium | medium-high |\n"
            "| sol_03_policy_reset | medium | medium | medium-high | medium |\n\n"
            "_Generated by local-llm mode._"
        )

    if td_case:
        return (
            "# Parity Report\n\n"
            "## Findings\n"
            "- sol_00_status_quo fails both turnaround and load-reduction targets.\n"
            "- sol_03_client_cpq_portal is strategically attractive but fails current budget discipline.\n"
            "- sol_02_l1_estimator_gate reaches speed targets fastest, but creates pricing-risk if launched before calibration.\n"
            "- sol_01_shadow_mode_matrix is slower in short horizon, but best satisfies reversibility and accuracy constraints.\n\n"
            "## Decision Logic\n"
            "- immediate speed without calibration is weaker than a staged path with accuracy control.\n"
            "- the preferred sequence is shadow-mode validation first, controlled delegation second.\n\n"
            "## Traceability\n"
            "- solutions/SolutionPortfolio.md:L1\n"
            "- problems/ComparisonAcceptanceSpec.md:L1\n\n"
            "_Generated by local-llm mode._"
        )

    return (
        "# Parity Report\n\n"
        "## Findings\n"
        "- sol_02_architecture_slice dominates sol_00_status_quo on target criteria.\n"
        "- sol_01_process_rewire and sol_03_policy_reset remain viable with different tradeoffs.\n"
        "- parity validity: usable with minor unknown penalties.\n\n"
        "## Decision Logic\n"
        "- architecture-first move gives the strongest effect under current assumptions.\n"
        "- process rewire remains a safer support option if risk tolerance is lower.\n\n"
        "## Traceability\n"
        "- solutions/SolutionPortfolio.md:L1\n"
        "- problems/ComparisonAcceptanceSpec.md:L1\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_conflict_routing(payload: Dict[str, Any]) -> str:
    return (
        "# Conflict Records\n\n"
        "## conflict_01\n"
        "- conflict_type: quality-attribute conflict\n"
        "- layers_involved: requirements,functional\n"
        "- viewpoints_involved: analyst,architect\n"
        "- method_selected: ATAM\n"
        "- selection_rationale: tradeoff between speed and reliability\n"
        "- resolution_status: resolved\n\n"
        "## conflict_02\n"
        "- conflict_type: alternative ranking conflict\n"
        "- layers_involved: business_model,allocation\n"
        "- viewpoints_involved: strategist,operator,client\n"
        "- method_selected: MCDA\n"
        "- selection_rationale: need explicit weighted comparison\n"
        "- resolution_status: resolved\n\n"
        "_Generated by local-llm mode._"
    )


def _local_build_selection_bundle(payload: Dict[str, Any]) -> str:
    mode = str(payload.get("solution_output", "selected_solutions"))
    selection_context = " ".join(
        [
            str(payload.get("solution_portfolio", "")),
            str(payload.get("selected_solutions", "")),
        ]
    ).lower()
    td_case = _contains_any(selection_context, ["shadow_mode_matrix", "l1_estimator_gate", "client_cpq_portal"])
    if mode == "selected_solutions":
        if td_case:
            return (
                "# Selected Solutions\n\n"
                "- sol_01_shadow_mode_matrix\n"
                "- sol_02_l1_estimator_gate\n\n"
                "Rejected:\n"
                "- sol_00_status_quo (preserves bottleneck and hidden losses)\n"
                "- sol_03_client_cpq_portal (fails current budget and rollout discipline)\n\n"
                "_Generated by local-llm mode._"
            )
        return (
            "# Selected Solutions\n\n"
            "- sol_02_architecture_slice\n"
            "- sol_01_process_rewire\n\n"
            "Rejected:\n"
            "- sol_00_status_quo (fails acceptance constraints)\n"
            "- sol_03_policy_reset (higher risk exposure under current horizon)\n\n"
            "_Generated by local-llm mode._"
        )
    if mode == "adr":
        if td_case:
            return (
                "# ADR-001: Solution Selection\n\n"
                "## Context\n"
                "- The current quotation flow overloads the Technical Director and slows client response.\n"
                "- Acceptance requires faster turnaround without losing pricing accuracy or harming production SLA.\n\n"
                "## Decision\n"
                "- Choose sol_01_shadow_mode_matrix as the first step.\n"
                "- Promote sol_02_l1_estimator_gate only after shadow-mode accuracy is proven.\n\n"
                "## Rejected Alternatives\n"
                "- sol_00_status_quo: preserves the bottleneck and hidden cost.\n"
                "- sol_03_client_cpq_portal: exceeds current budget and implementation discipline.\n\n"
                "## Risks\n"
                "- expert resistance, misclassification of complex work, premature delegation.\n\n"
                "## Evidence Basis\n"
                "- problems/ComparisonAcceptanceSpec.md:L1\n"
                "- solutions/ParityReport.md:L1\n"
                "- solutions/ConflictRecords.md:L1\n\n"
                "## Consequences\n"
                "- short-term speed gain is deferred in exchange for safer validation.\n"
                "- if the shadow stage succeeds, the organization gets a controlled path to scale quotation throughput.\n\n"
                "_Generated by local-llm mode._"
            )
        return (
            "# ADR-001: Solution Selection\n\n"
            "## Context\n"
            "- Selection based on ComparisonAcceptanceSpec and parity/conflict outputs.\n\n"
            "## Decision\n"
            "- Choose sol_02_architecture_slice as primary and sol_01_process_rewire as support.\n\n"
            "## Rejected Alternatives\n"
            "- sol_00_status_quo: does not satisfy constraints.\n"
            "- sol_03_policy_reset: weaker parity score.\n\n"
            "## Risks\n"
            "- integration complexity; adoption lag.\n\n"
            "## Evidence Basis\n"
            "- problems/ComparisonAcceptanceSpec.md:L1\n"
            "- solutions/ParityReport.md:L1\n"
            "- solutions/ConflictRecords.md:L1\n\n"
            "## Consequences\n"
            "- implementation starts with a bounded architecture slice instead of a full transformation.\n"
            "- the team keeps a fallback path if adoption or technical fit is weaker than expected.\n\n"
            "_Generated by local-llm mode._"
        )
    if mode == "runbook":
        if td_case:
            return (
                "# Runbook\n\n"
                "## Preconditions\n"
                "- owner for the pilot is assigned.\n"
                "- standard request categories are explicitly defined.\n\n"
                "## Execution Steps\n"
                "1. Extract quotation heuristics from the Technical Director into a controlled matrix.\n"
                "2. Run shadow mode on standard requests and compare output against expert pricing.\n"
                "3. Enable L1 routing only after accuracy thresholds are met.\n"
                "4. Monitor quote speed, pricing delta, conversion, and production SLA weekly.\n\n"
                "## Success Criteria\n"
                "- delegated quotations stay within accepted pricing tolerance.\n"
                "- production SLA remains stable while quote turnaround improves.\n\n"
                "_Generated by local-llm mode._"
            )
        return (
            "# Runbook\n\n"
            "## Preconditions\n"
            "- owners and success criteria are aligned.\n\n"
            "## Execution Steps\n"
            "1. Align owners and success criteria.\n"
            "2. Launch limited architecture slice.\n"
            "3. Measure indicators weekly.\n"
            "4. Expand only if acceptance thresholds are stable.\n\n"
            "## Success Criteria\n"
            "- acceptance thresholds remain stable across the pilot window.\n"
            "- no material regressions appear in the monitored indicators.\n\n"
            "_Generated by local-llm mode._"
        )
    if td_case:
        return (
            "# Rollback Plan\n\n"
            "## Triggers\n"
            "- Trigger rollback if pricing delta breaches tolerance or production SLA degrades.\n"
            "- Trigger rollback if delegated routing starts misclassifying non-standard work.\n\n"
            "## Actions\n"
            "- Remove delegated quotation authority and route requests back to the Technical Director.\n"
            "- Re-open shadow mode and recalibrate the estimation matrix before any re-launch.\n\n"
            "## Safe State\n"
            "- all new quotations return to the expert-controlled baseline flow.\n\n"
            "_Generated by local-llm mode._"
        )
    return (
        "# Rollback Plan\n\n"
        "## Triggers\n"
        "- Trigger rollback if unresolved_critical_gaps increases for 2 consecutive checks.\n\n"
        "## Actions\n"
        "- Revert to previous baseline process and freeze expansion.\n"
        "- Re-open problem framing with updated evidence.\n\n"
        "## Safe State\n"
        "- the system returns to the previous stable operating baseline.\n\n"
        "_Generated by local-llm mode._"
    )


def _short_lines(text: str, max_lines: int = 4) -> List[str]:
    meta_prefixes = (
        "id:",
        "artifact_type:",
        "workspace_id:",
        "source:",
        "traceability:",
        "file:",
        "status:",
        "owner_role:",
        "valid_until:",
        "based_on:",
        "stage:",
        "state:",
        "parent_refs:",
        "source_refs:",
        "evidence_refs:",
        "viewpoints:",
        "epistemic_status:",
        "assurance_level:",
        "gate_status:",
        "violated_principles:",
        "next_expected_artifacts:",
        "created_at:",
        "updated_at:",
    )
    lines: List[str] = []
    for raw in str(text).splitlines():
        s = raw.strip()
        low = s.lower()
        if not s:
            continue
        if s in {"---", "```", "```markdown", "```json"}:
            continue
        if low.startswith(meta_prefixes):
            continue
        if low.startswith("### директория:") or low.startswith("#### файл:"):
            continue
        s = re.sub(r"^#+\s*", "", s)
        if s.startswith(("- ", "* ", "+ ")):
            s = s[2:].strip()
        s = re.sub(r"^\d+[.)]\s+", "", s)
        s = re.sub(r"[*_`]+", "", s)
        s = re.sub(r"\s+", " ", s).strip()
        if not s:
            continue
        low = s.lower()
        if low.startswith(meta_prefixes):
            continue
        if low.startswith(("source:", "traceability:", "generated by ", "sourcetext:", "selectionrationale:")):
            continue
        if re.match(r"^sol[_0-9a-z-]+$", low):
            continue
        if re.match(r'^"?(name|measurementprocedure|artifact|class|text|role|method|decision|context|consequences|status|date)"?\s*:', low):
            continue
        if re.match(r"^(type|assurancelevel|assurance_level|conflicttype|layersinvolved|viewpointsinvolved|methodselected|resolutionstatus|artifacttype|workspaceid|updatedat|claimscount|edgescount)\s*:", low):
            continue
        if low.startswith("claim::") or "| class=" in low or "| artifact=" in low or "| text=" in low:
            continue
        if re.match(r"^[a-z0-9_./:-]+$", low) and len(low) < 40:
            continue

        candidates = [seg.strip(" -;,.") for seg in re.split(r"(?<=[.!?])\s+", s) if seg.strip(" -;,.")]
        if not candidates:
            candidates = [s]
        for candidate in candidates:
            c_low = candidate.lower()
            words = re.findall(r"[A-Za-zА-Яа-я0-9%+-]+", candidate)
            if len(candidate) < 12:
                continue
            if len(words) < 3:
                continue
            if re.match(r"^[a-z0-9_./:-]+$", c_low) and len(c_low) < 60:
                continue
            if candidate not in lines:
                lines.append(candidate)
            if len(lines) >= max_lines:
                return lines[:max_lines]
    return lines[:max_lines]


def _td_bottleneck_case(artifacts: Dict[str, Any]) -> bool:
    blob = " ".join(
        [
            str(artifacts.get("intake/normalized_case.md", "")),
            str(artifacts.get("problems/SelectedProblemCard.md", "")),
            str(artifacts.get("problems/ComparisonAcceptanceSpec.md", "")),
            str(artifacts.get("solutions/ParityReport.md", "")),
            str(artifacts.get("decisions/ADR-001.md", "")),
            str(artifacts.get("operation/Runbook.md", "")),
        ]
    ).lower()
    return any(
        token in blob
        for token in [
            "technical director",
            "технического директора",
            "технічного директора",
            "тд",
            "time_to_quote",
            "7-10",
            "7–10",
            "shadow mode",
            "l1 estimator",
            "bant",
        ]
    )


def _pick_lines(lines: List[str], keywords: List[str], limit: int = 2) -> List[str]:
    picked = [ln for ln in lines if any(k in ln.lower() for k in keywords)]
    return picked[:limit]


def _sentence(text: str) -> str:
    out = str(text).strip().strip(" -;,.")
    if not out:
        return ""
    if out[-1] not in ".!?":
        out += "."
    return out


def _join_sentences(lines: List[str], fallback: str, limit: int = 2) -> str:
    selected = [_sentence(ln) for ln in lines[:limit] if ln.strip()]
    selected = [x for x in selected if x]
    if not selected:
        return _sentence(fallback)
    return " ".join(selected)


def _epistemic_triplet(facts: str, interpretations: str, hypotheses: str) -> str:
    return (
        f"**Факты:** {facts}\n"
        f"**Интерпретации:** {interpretations}\n"
        f"**Гипотезы / следующий шаг:** {hypotheses}"
    )


def _local_analytical_section_body(
    title: str,
    rel: str,
    text: str,
    artifacts: Dict[str, Any],
) -> str:
    lines = _short_lines(text, max_lines=12)
    selected_problem = _short_lines(str(artifacts.get("problems/SelectedProblemCard.md", "")), max_lines=8)
    acceptance = _short_lines(str(artifacts.get("problems/ComparisonAcceptanceSpec.md", "")), max_lines=8)
    parity = _short_lines(str(artifacts.get("solutions/ParityReport.md", "")), max_lines=8)
    runbook = _short_lines(str(artifacts.get("operation/Runbook.md", "")), max_lines=8)
    evidence = _short_lines(str(artifacts.get("evidence/evidence_graph.md", "")), max_lines=8)
    td_case = _td_bottleneck_case(artifacts)

    if title == "Action Context":
        return _epistemic_triplet(
            "GAP: source artifact missing or empty.",
            "Без исходного контекста снижается полнота доказательной базы и теряется часть первичных нюансов запроса.",
            f"Восстановить `{rel}`, затем повторить сборку отчета.",
        )

    if title == "Bounded Context":
        if td_case:
            return _epistemic_triplet(
                "В фокусе узкое место в контуре пресейла: типовые и нетиповые запросы без развилки попадают на одного перегруженного технического эксперта.",
                "Решение должно ускорить выдачу оценки, удержать точность расчета, не ухудшить производственный SLA и остаться обратимым в пределах пилота.",
                "Менять нужно не всю компанию, а конкретный узел маршрутизации, оценки и эскалации.",
            )
        focus = _join_sentences(
            _pick_lines(lines, ["problem", "узк", "bottleneck", "маршрут", "заяв", "director", "технич"]),
            "В фокусе находится ограниченный контур принятия решения и прохождения заявки через узкое место.",
        )
        constraints = _join_sentences(
            _pick_lines(lines, ["target", "constraint", "огранич", "±", "sla", "budget", "вериф", "shadow"]),
            "Контур анализа ограничен критериями приемки, точностью оценки, бюджетом и защитой операционного ядра.",
        )
        return _epistemic_triplet(
            focus,
            constraints,
            "Менять нужно не всю систему сразу, а конкретный узел маршрутизации, оценки и эскалации.",
        )

    if title == "Normalized Case":
        if td_case:
            return _epistemic_triplet(
                "Небольшая производственная компания передает оценку почти всех клиентских запросов Техническому директору, из-за чего ответ клиенту задерживается на несколько дней.",
                "Продажи зависят от скорости реакции, но самый дорогой производственный ресурс отвлекается на пресейл и перестает выполнять свою основную функцию.",
                "Требуется отделить типовую оценку от перегруженного экспертного контура и ввести управляемую маршрутизацию.",
            )
        observed = _join_sentences(lines[:3], "Кейс описывает операционный разрыв между входящим спросом и скоростью ответа.")
        impact = _join_sentences(
            _pick_lines(lines, ["проблем", "delay", "дн", "клієн", "client", "втра", "lost", "конкур"]),
            "Задержка ответа ухудшает конверсию, перегружает ключевой ресурс и ослабляет позицию компании на рынке.",
        )
        return _epistemic_triplet(
            observed,
            impact,
            "Требуется отделить типовую оценку от перегруженного экспертного контура.",
        )

    if title == "4-Layer Model":
        if td_case:
            return (
                "- Как выглядит сбой по слоям: бизнес-модель страдает из-за дорогого пресейла и потери клиентов, процесс не имеет L1-маршрутизации, инструменты оценки не отчуждают знания, а роли продаж и производства конфликтуют между собой.\n"
                "- Почему это важно: проблема не локальна и не сводится к одному человеку, поэтому точечный административный нажим не даст устойчивого результата.\n"
                "- Что из этого следует: нужно одновременно перепроектировать процесс маршрутизации, инструменты оценки и распределение полномочий."
            )
        return (
            f"- Как выглядит сбой по слоям: {_join_sentences(lines[:4], 'Разрыв проявляется на уровне бизнес-модели, процесса, инструментов и ролей.', limit=4)}\n"
            "- Почему это важно: проблема не локальна и не сводится к одному человеку, поэтому точечный административный нажим не даст устойчивого результата.\n"
            "- Что из этого следует: нужно одновременно перепроектировать процесс маршрутизации, инструменты оценки и распределение полномочий."
        )

    if title == "Viewpoint Matrix":
        viewpoints = []
        for vp in ["strategist", "analyst", "operator", "architect", "critic", "client"]:
            if str(artifacts.get(f"viewpoints/{vp}.md", "")).strip():
                viewpoints.append(vp)
        coverage_map = {
            "strategist": "стратег",
            "analyst": "аналитик",
            "operator": "оператор",
            "architect": "архитектор",
            "critic": "критик",
            "client": "клиент",
        }
        coverage = ", ".join(coverage_map.get(vp, vp) for vp in viewpoints) if viewpoints else "точки зрения не собраны"
        conflicts = "Конфликты между точками зрения явно не зафиксированы." if "no explicit conflicts" in text.lower() else "Между точками зрения есть напряжение, требующее отдельного разрешения."
        return (
            f"- Какие точки зрения покрыты: {coverage}.\n"
            f"- Что показывает матрица взглядов: {conflicts}\n"
            "- Почему это важно: совпадение разных перспектив усиливает надежность диагноза и снижает риск слепых зон."
        )

    if title == "Characterization Passport":
        if td_case:
            return (
                "- Что признано слабым звеном: система не умеет автономно обрабатывать типовые кейсы и поэтому пропускает весь входящий поток через перегруженный экспертный контур.\n"
                "- Почему это важно: пока автономность равна нулю, масштабирование потока автоматически разрушает срок реакции и качество исполнения.\n"
                "- Что это означает для дальнейших стадий: решение должно повышать автономность, но не ломать защиту производственного ядра."
            )
        return (
            f"- Что признано слабым звеном: {_join_sentences(_pick_lines(lines, ['weak', 'слаб', 'triage', 'автоном', 'routing', 'маршрути']), 'Система не умеет автономно обрабатывать типовые кейсы без входа в экспертный контур.')}\n"
            "- Почему это важно: пока автономность равна нулю, масштабирование потока автоматически разрушает срок реакции и качество исполнения.\n"
            "- Что это означает для дальнейших стадий: решение должно повышать автономность, но не ломать защиту производственного ядра."
        )

    if title == "Indicator Set":
        if td_case:
            return (
                "- Какие метрики взяты в управление: скорость выдачи оценки, точность расчета, доля автономной маршрутизации, конверсия в продажу и защита производственного SLA.\n"
                "- Почему это важно: без измеримых индикаторов команда будет спорить о впечатлениях вместо контроля реального эффекта.\n"
                "- Что делать дальше: привязать переходы между фазами решения к этим метрикам, а не к субъективной уверенности участников."
            )
        metrics = _pick_lines(lines, ["time", "quote", "sla", "conversion", "qualification", "rate", "стоим", "срок", "конверс"])
        return (
            f"- Какие метрики взяты в управление: {_join_sentences(metrics, 'Скорость ответа, точность оценки, доля автономной маршрутизации, конверсия и защита производственного SLA.', limit=4)}\n"
            "- Почему это важно: без измеримых индикаторов команда будет спорить о впечатлениях вместо контроля реального эффекта.\n"
            "- Что делать дальше: привязать переходы между фазами решения к этим метрикам, а не к субъективной уверенности участников."
        )

    if title == "Problem Archive":
        if td_case:
            return (
                "- Корневая причина: в системе отсутствует отдельный контур типовой оценки и фильтрации входящих запросов, поэтому вся нагрузка стягивается на одного эксперта.\n"
                "- Механизм поломки: даже стандартные заявки без предварительной квалификации попадают к Техническому директору, из-за чего очередь растет быстрее, чем система успевает ее обрабатывать.\n"
                "- К чему это ведет: компания теряет скорость ответа, перегружает производственный контур и превращает пресейл в источник скрытых убытков."
            )
        cause = _join_sentences(_pick_lines(lines, ["причин", "cause", "отсутств", "нет", "missing"]), "Корневая причина связана с отсутствием отчужденной логики и фильтрации на входе.")
        mechanism = _join_sentences(_pick_lines(lines, ["mechan", "влиян", "100%", "маршрут", "эскалац", "triage"]), "Все заявки проходят через единый экспертный узел без промежуточного отбора.")
        return (
            f"- Корневая причина: {cause}\n"
            f"- Механизм поломки: {mechanism}\n"
            "- К чему это ведет: растет очередь оценки, ухудшается конверсия и появляется прямой ущерб производственному контуру."
        )

    if title == "Problem Portfolio":
        if td_case:
            return (
                "- Какие проблемы отобраны в работу: в портфель вошли три связанных проблемы: bottleneck на Техническом директоре, эскалация неквалифицированных лидов в экспертный контур и отсутствие инструментов для отчуждения логики оценки.\n"
                "- Почему это важно: портфель показывает, что лечить нужно не только скорость оценки, но и качество входящего потока и перенос знаний из головы эксперта в воспроизводимую систему.\n"
                "- Что из этого следует: решение должно сочетать делегирование типовых кейсов, квалификацию нестандартных кейсов и формализацию правил расчета."
            )
        return (
            f"- Какие проблемы отобраны в работу: {_join_sentences(lines[:3], 'В работу взяты проблема централизации оценки и проблема слепой эскалации неквалифицированных лидов.', limit=3)}\n"
            "- Почему это важно: портфель показывает, что лечить нужно не только узкое место в оценке, но и качество входящего потока.\n"
            "- Что из этого следует: решение должно сочетать делегирование типовых кейсов и фильтрацию сложных кейсов до входа в экспертный контур."
        )

    if title == "Selected Problem Card":
        if td_case:
            return (
                "- Какая проблема выбрана как ключевая: выбрана проблема отчуждения типовой оценки от Технического директора, потому что именно она является главным bottleneck и единой точкой отказа в пресейле.\n"
                "- Почему именно она: эта проблема одновременно влияет на скорость ответа, стоимость пресейла, загрузку производства и потерю клиентов, а значит дает наибольший системный эффект при корректном решении.\n"
                "- Что это означает для решения: приоритет отдан проблеме, которая расшивает основное узкое горлышко и допускает поэтапное, обратимое внедрение."
            )
        selected = _join_sentences(selected_problem[:3] or lines[:3], "Выбрана проблема отчуждения типовой оценки от самого дорогого производственного ресурса.", limit=3)
        targets = _join_sentences(acceptance[:3], "Цель состоит в отделении типовой оценки от экспертного контура без потери точности.", limit=2)
        return (
            f"- Какая проблема выбрана как ключевая: {selected}\n"
            f"- Почему именно она: {targets}\n"
            "- Что это означает для решения: приоритет отдан проблеме, которая расшивает главное узкое горлышко и дает обратимый путь внедрения."
        )

    if title == "Comparison & Acceptance Spec":
        if td_case:
            return (
                "- Какие условия считаются обязательными: решение должно ускорить обработку типовых запросов, удержать точность расчета в допустимом коридоре, не просадить производственный SLA и проходить через проверяемый пилот.\n"
                "- Почему это важно: критерии приемки отсекают решения, которые ускоряют продажи ценой убытков на производстве или потери контроля над качеством оценки.\n"
                "- Что это означает для выбора: победит не самое быстрое решение, а то, которое одновременно проходит по скорости, точности, бюджету и обратимости."
            )
        return (
            f"- Какие условия считаются обязательными: {_join_sentences(acceptance[:4], 'Решение должно ускорить типовые ответы, удержать точность, не просадить SLA и пройти теневую проверку.', limit=4)}\n"
            "- Почему это важно: критерии приемки отсекают решения, которые красивы на бумаге, но опасны для маржи или для производства.\n"
            "- Что это означает для выбора: скорость сама по себе недостаточна, если она покупается ценой ошибки в себестоимости."
        )

    if title == "Solution Portfolio":
        if td_case:
            return (
                "- Какие альтернативы рассмотрены: рассмотрены четыре класса действий: сохранить статус-кво, сначала извлечь эвристики в Shadow Mode, быстро передать типовые расчеты на L1-контур или радикально вынести оценку в клиентский CPQ-портал.\n"
                "- Почему это важно: наличие альтернатив разного масштаба позволяет сравнить не только скорость эффекта, но и стоимость внедрения, риск ошибки и обратимость.\n"
                "- Что из этого следует: финальное решение должно быть выбрано через trade-off между скоростью, точностью и управляемостью внедрения."
            )
        return (
            f"- Какие альтернативы рассмотрены: {_join_sentences(lines[:4], 'Рассмотрены статус-кво, постепенное отчуждение оценки, немедленное делегирование и радикальная ИТ-автоматизация.', limit=4)}\n"
            "- Почему это важно: наличие разных классов альтернатив позволяет сравнить не только стоимость, но и обратимость, риск и скорость эффекта.\n"
            "- Что из этого следует: финальное решение должно быть выбрано через trade-off между скоростью, точностью и управляемостью внедрения."
        )

    if title == "Parity Plan/Report":
        if td_case:
            return (
                "- Что показало сравнение альтернатив: статус-кво проваливает целевые метрики, CPQ-портал выглядит слишком дорогим и радикальным, L1-делегирование дает самый быстрый эффект, но без калибровки несет риск ошибки, а Shadow Mode лучше всего проходит по критериям точности и обратимости.\n"
                "- Почему это важно: parity-проверка отделяет реально приемлемые решения от тех, которые либо слишком рискованны, либо не проходят текущие ограничения по бюджету и качеству.\n"
                "- Что это означает для отбора: безопасный пошаговый сценарий выигрывает у быстрых, но плохо контролируемых ускорителей."
            )
        return (
            f"- Что показало сравнение альтернатив: {_join_sentences(parity[:4] or lines[:4], 'Часть вариантов проваливается по бюджету, часть по точности, а безопасный вариант выигрывает за счет управляемости.', limit=4)}\n"
            "- Почему это важно: parity-проверка отделяет реально приемлемые решения от тех, которые нарушают жесткие ограничения.\n"
            "- Что это означает для отбора: безопасный пошаговый сценарий сильнее радикальных и рискованных ускорителей."
        )

    if title == "Tradeoff Resolution":
        if td_case:
            return (
                "- Какой конфликт пришлось разрешать: главный конфликт проходит между скоростью ответа клиенту и защитой точности, маржи и производственного SLA.\n"
                "- Почему решение принято именно так: при жестком ограничении на точность скорость не может быть первичной ценностью, поэтому сначала выбран безопасный этап верификации, а затем ускорение.\n"
                "- Что из этого следует: выбран поэтапный сценарий, где сначала снимается неопределенность, а потом масштабируется эффект."
            )
        return (
            f"- Какой конфликт пришлось разрешать: {_join_sentences(lines[:3], 'Главный конфликт проходит между скоростью ответа и защитой точности/маржи.', limit=3)}\n"
            "- Почему решение принято именно так: при жестком ограничении на точность скорость не может быть первичной ценностью.\n"
            "- Что из этого следует: выбран поэтапный сценарий, где сначала снимается неопределенность, а потом масштабируется эффект."
        )

    if title == "ADR":
        if td_case:
            return (
                "- Какое решение зафиксировано: принят гибридный сценарий `Shadow Mode -> L1 Estimator + BANT`, где сначала формализуются правила расчета и подтверждается точность, а затем запускается автономная обработка типовых кейсов.\n"
                "- Почему это важно: ADR связывает альтернативы, ограничения, причины выбора и последствия в одну управленческую рамку.\n"
                "- Что делать дальше: реализовать решение как контролируемый пилот, а не как мгновенную тотальную реформу."
            )
        adr_core = _join_sentences(lines[:4], "Зафиксирован поэтапный архитектурный выбор, который сначала снижает неопределенность, затем делегирует типовые операции.", limit=4)
        return (
            f"- Какое решение зафиксировано: {adr_core}\n"
            "- Почему это важно: ADR связывает альтернативы, ограничения, причины выбора и последствия в одну управленческую рамку.\n"
            "- Что делать дальше: реализовать решение как контролируемый пилот, а не как мгновенную тотальную реформу."
        )

    if title == "Runbook/Rollback/Impact Plan":
        if td_case:
            return (
                "- Как выглядит операционный план: сначала идет теневое тестирование матрицы расчета на реальных заявках, затем при подтверждении точности включается L1-контур для типовых кейсов и BANT-гейт для сложных.\n"
                "- Почему это важно: внедрение обратимо и не требует необратимого организационного прыжка в начале.\n"
                "- Что это означает для управления: пилот должен сопровождаться заранее утвержденным rollback-сценарием и метриками эффекта."
            )
        plan = _join_sentences(runbook[:4] or lines[:4], "План внедрения разбит на ограниченные фазы с явными триггерами запуска и отката.", limit=4)
        return (
            f"- Как выглядит операционный план: {plan}\n"
            "- Почему это важно: внедрение обратимо и не требует необратимого организационного прыжка в начале.\n"
            "- Что это означает для управления: пилот должен сопровождаться заранее утвержденным rollback-сценарием и метриками эффекта."
        )

    if title == "Evidence Status":
        if td_case:
            return (
                "- Что показывает доказательная база: ключевые выводы подтверждаются цепочкой артефактов от нормализации кейса и проблемной спецификации до parity-анализа, ADR и runbook.\n"
                "- Почему это важно: решение подтверждается не одним документом, а цепочкой согласованных артефактов.\n"
                "- Что это означает для качества вывода: уровень защищенности решения выше, чем при изолированном экспертном мнении."
            )
        if not evidence and not lines:
            return (
                "- Что зафиксировано: доказательная база неполна и не собрана в отдельный граф.\n"
                "- Почему это важно: без связанной evidence-модели труднее защищать решение перед руководством и повторно его проверять.\n"
                "- Что сделать: восстановить evidence-артефакты и повторить трассировку выводов."
            )
        return (
            f"- Что показывает доказательная база: {_join_sentences(evidence[:3] or lines[:3], 'Артефакты решения связаны между собой и поддерживают сквозную трассировку от симптомов к выбранному действию.', limit=3)}\n"
            "- Почему это важно: решение подтверждается не одним документом, а цепочкой согласованных артефактов.\n"
            "- Что это означает для качества вывода: уровень защищенности решения выше, чем при изолированном экспертном мнении."
        )

    if title == "Open Questions":
        if "[]" in text or not lines:
            return (
                "- Что остается неизвестным: явная очередь вопросов не сформирована, но количественные пробелы во входных данных сохраняются.\n"
                "- Почему это важно: без точной экономики процесса сложно посчитать ROI и темп масштабирования решения.\n"
                "- Что сделать: собрать стоимость часа ключевого эксперта, структуру воронки и долю типовых кейсов."
            )
        return (
            f"- Какие вопросы остаются открытыми: {_join_sentences(lines[:3], 'Часть количественных и организационных параметров еще не подтверждена.', limit=3)}\n"
            "- Почему это важно: открытые вопросы ограничивают точность прогноза эффекта и рисков.\n"
            "- Что сделать: закрыть недостающие данные в рамках пилота и следующего цикла переоценки."
        )

    if title == "Escalation/Re-entry conditions":
        return (
            "- Когда нужна эскалация: при невозможности удержать точность, при подтвержденном негативном эффекте на операционное ядро или при провале стандартизации типовых кейсов.\n"
            "- Почему это важно: re-entry условия защищают от замалчивания неудачного пилота и от ложного чувства прогресса.\n"
            "- Что делать: заранее согласовать пороги эскалации и владельца решения на следующий цикл."
        )

    observed = _join_sentences(lines[:2], "Факты описаны частично.")
    because = _join_sentences(lines[2:4], "Дополнительные ограничения не раскрыты полностью.")
    therefore = _join_sentences(lines[4:6], "Нужна синхронизация решений, критериев приемки и плана внедрения.")
    return _epistemic_triplet(observed, because, therefore)


def _local_build_reporting_analytical(payload: Dict[str, Any]) -> str:
    sections = payload.get("analytical_sections", [])
    artifacts = payload.get("artifact_context", {})
    missing = set(payload.get("missing_sources", []))

    parts = ["# Аналитический полный отчет", ""]
    for section in sections:
        idx = str(section.get("index", ""))
        title = str(section.get("title", ""))
        rel = str(section.get("source", ""))
        text = str(artifacts.get(rel, ""))

        if not text or rel in missing:
            body = (
                "- Что зафиксировано: GAP: source artifact missing or empty.\n"
                "- Почему это важно: без этого источника отчет теряет часть доказательной основы и управленческой надежности.\n"
                f"- Что сделать: восстановить `{rel}`, затем повторить сборку отчета."
            )
        else:
            body = _local_analytical_section_body(title, rel, text, artifacts)

        parts.extend([f"## {idx}. {title}", f"- source: {rel}", body, ""])

    parts.extend(
        [
            "## Трассируемость",
            "- Выводы сформированы только на базе входных артефактов кейса без добавления новых фактов.",
            "- Для каждого раздела сохраняется ссылка на исходный артефакт.",
            "",
            "_Generated by local-llm mode._",
        ]
    )
    return "\n".join(parts)


def _local_build_reporting_executive(payload: Dict[str, Any]) -> str:
    sections = payload.get("executive_sections", [])
    artifacts = payload.get("artifact_context", {})
    selected = str(artifacts.get("solutions/SelectedSolutions.md", ""))
    selected_lines = []
    confirmed_actions: List[str] = []
    pilot_hypotheses: List[str] = []
    for ln in selected.splitlines():
        s = ln.strip()
        if not s.startswith("- "):
            continue
        val = s[2:].strip()
        low_val = val.lower()
        if low_val.startswith("confirmed_action:"):
            confirmed_actions.append(val.split(":", 1)[1].strip())
            continue
        if low_val.startswith("pilot_hypothesis:"):
            pilot_hypotheses.append(val.split(":", 1)[1].strip())
            continue
        if not val.lower().startswith("sol_"):
            continue
        if "<-" in val:
            continue
        selected_lines.append(val)
    selected_lines = selected_lines[:3]

    analytical = _short_lines(str(artifacts.get("reports/Analytical_Full_Report.md", "")), max_lines=20)
    normalized = _short_lines(str(artifacts.get("intake/normalized_case.md", "")), max_lines=8)
    selected_problem = _short_lines(str(artifacts.get("problems/SelectedProblemCard.md", "")), max_lines=10)
    acceptance = _short_lines(str(artifacts.get("problems/ComparisonAcceptanceSpec.md", "")), max_lines=10)
    parity = _short_lines(str(artifacts.get("solutions/ParityReport.md", "")), max_lines=10)
    portfolio = _short_lines(str(artifacts.get("solutions/SolutionPortfolio.md", "")), max_lines=12)
    adr = _short_lines(str(artifacts.get("decisions/ADR-001.md", "")), max_lines=10)
    runbook = _short_lines(str(artifacts.get("operation/Runbook.md", "")), max_lines=10)
    rollback = _short_lines(str(artifacts.get("operation/RollbackPlan.md", "")), max_lines=10)
    evidence = _short_lines(str(artifacts.get("evidence/evidence_graph.md", "")), max_lines=8)
    refresh = _short_lines(str(artifacts.get("evidence/refresh_report.md", "")), max_lines=8)
    missing_sources = set(payload.get("missing_sources", []))
    raw_case_blob = " ".join(
        [
            str(artifacts.get("intake/normalized_case.md", "")),
            str(artifacts.get("problems/SelectedProblemCard.md", "")),
            str(artifacts.get("problems/ComparisonAcceptanceSpec.md", "")),
            str(artifacts.get("solutions/ParityReport.md", "")),
            str(artifacts.get("decisions/ADR-001.md", "")),
            str(artifacts.get("operation/Runbook.md", "")),
        ]
    ).lower()

    human_names: Dict[str, str] = {}
    current_id = ""
    for raw in str(artifacts.get("solutions/SolutionPortfolio.md", "")).splitlines():
        s = raw.strip()
        if s.startswith("## "):
            match = re.match(r"##\s+(sol[_0-9a-z-]+)\s*[:-]?\s*(.*)$", s, flags=re.IGNORECASE)
            if not match:
                current_id = ""
                continue
            current_id = match.group(1).strip()
            title = match.group(2).strip(" -:")
            if title:
                human_names[current_id] = title
            continue
        if current_id and s.startswith("- ") and ":" in s:
            key, value = s[2:].split(":", 1)
            if key.strip().lower() in {"title", "name", "label"} and value.strip():
                human_names[current_id] = value.strip()

    recommendation_items = []
    hybrid_selected = "sol_01" in selected.lower() and "sol_02" in selected.lower()
    if hybrid_selected:
        recommendation_items = [
            "- Подтвержденное действие: теневое извлечение эвристик Технического директора. Сначала формализовать правила расчета и проверить их на реальных заявках без изменения клиентского опыта.",
            "- Подтвержденное действие: переход на L1-оценку типовых кейсов. После подтверждения точности передать 80% типовых запросов на выделенный L1-контур.",
            "- Подтвержденное действие: BANT-гейт для нестандартных кейсов. Допускать эскалацию к Техническому директору только после квалификации бюджета и сроков.",
        ]
    elif pilot_hypotheses:
        recommendation_items = [
            "- Гипотеза пилота: на этом цикле не внедрять целевую архитектуру, а собрать недостающие данные и повторить выбор."
        ]
    else:
        for item in selected_lines:
            label = human_names.get(item, item.replace("_", " "))
            prefix = "Подтвержденное действие" if item in confirmed_actions or confirmed_actions else "Гипотеза пилота"
            recommendation_items.append(
                f"- {prefix}: {label}. Вариант взят в работу под текущие ограничения по точности, скорости и обратимости."
            )
    recommendations = (
        "\n".join(recommendation_items)
        if recommendation_items
        else "- GAP: рекомендации не опубликованы, так как не зафиксирован согласованный набор выбранных решений."
    )

    td_case = any(
        k in raw_case_blob
        for k in [
            "technical director",
            "технического директора",
            "технічного директора",
            "тд",
            "time_to_quote",
            "7-10",
            "7–10",
            "shadow mode",
            "l1 estimator",
            "bant",
        ]
    )

    if td_case:
        default_sections = {
            "1": "Компания теряет скорость ответа клиенту и перегружает производственный контур, потому что оценка типовых запросов завязана на одном дефицитном эксперте. Это создает одновременно сбой в продажах, скрытый рост стоимости пресейла и давление на производство.",
            "2": "Главная проблема состоит в том, что типовая оценка не отчуждена от Технического директора. Любая входящая заявка, включая некачественные и слабые лиды, проходит через один и тот же экспертный узел и превращает его в единую точку отказа.",
            "3": "Ключевой конфликт проходит между скоростью ответа рынку и безопасностью производственного ядра. Если ускорять поток без контроля точности, компания рискует продавать в минус; если сохранять ручной экспертный режим, компания продолжает терять сделки и пропускную способность.",
            "4": recommendations,
            "5": "Выбран не самый быстрый, а самый управляемый путь. Сначала снимается неопределенность через Shadow Mode и проверку точности, затем включается ускорение через L1-оценку и BANT-гейт. Такой порядок лучше проходит ограничения по точности, бюджету и обратимости.",
            "6": "Основные риски связаны с сопротивлением отчуждению знаний, ложной типизацией сложных кейсов и подменой реального эффекта красивыми метриками скорости. Отдельный риск состоит в том, что ускорение продаж может быть достигнуто ценой ухудшения производственного SLA.",
            "7": "Откат должен срабатывать немедленно при выходе за порог точности, при появлении убыточных сделок или при просадке производственного SLA. Маршрутизация заявок должна быстро возвращаться в экспертный контур без организационного хаоса.",
            "8": "Ближайший шаг — короткий пилот с теневым тестированием на типовых заявках, назначением владельца внедрения и заранее согласованными критериями перехода в боевой режим.",
            "9": "Измерять нужно скорость выдачи оценки, долю заявок вне экспертного контура, отклонение новой оценки от экспертной, конверсию в договор и влияние на производственный SLA. Без этого невозможно доказать, что ускорение действительно создает, а не уничтожает ценность.",
            "10": "Уверенность в структурном диагнозе высокая, потому что он поддержан несколькими артефактами и разными точками зрения. Уверенность в масштабе экономического эффекта средняя до завершения пилота и сбора недостающих цифр.",
        }
    else:
        case_text = _join_sentences(
            normalized[:2] or analytical[:3] or selected_problem[:3],
            "Проект находится в точке, где нужно одновременно удержать темп реализации и снизить риск неверного выбора.",
            limit=3,
        )
        acceptance_text = _join_sentences(
            acceptance[:2] + refresh[:2],
            "Решение должно пройти через ограничения по бюджету, качеству, обратимости и условиям повторной проверки.",
            limit=3,
        )
        parity_text = _join_sentences(
            parity[:2] + adr[:2] + portfolio[:1],
            "Альтернативы сравниваются через ограничения, риск, обратимость и ожидаемый эффект.",
            limit=3,
        )
        rollout_text = _join_sentences(
            runbook[:2] + rollback[:1],
            "Следующий шаг — ограниченный пилот с владельцем, сроком, rollback-сценарием и измеримыми критериями результата.",
            limit=3,
        )
        default_sections = {
            "1": case_text,
            "2": _join_sentences(selected_problem[:3], "Ключевая проблема — рассогласование между целевой логикой проекта и фактической организацией исполнения.", limit=3),
            "3": _join_sentences(
                _pick_lines(selected_problem + acceptance + parity, ["скор", "risk", "устойчив", "quality", "обратим", "срок", "budget"], limit=3),
                "Главный конфликт интересов проходит между потребностью в быстрых изменениях и требованиями к устойчивости результата.",
                limit=3,
            ),
            "4": recommendations,
            "5": parity_text,
            "6": _join_sentences(
                runbook[:2] + rollback[:2] + refresh[:2],
                "Сохраняются риски по полноте доказательной базы, согласованности ролей и реалистичности темпа внедрения.",
                limit=3,
            ),
            "7": _join_sentences(
                rollback[:3],
                "Откат активируется при ухудшении ключевых метрик в двух последовательных контрольных периодах.",
                limit=3,
            ),
            "8": rollout_text,
            "9": acceptance_text,
            "10": _join_sentences(
                evidence[:2] + refresh[:2],
                "Уровень уверенности рабочий для пилота, но не финальный для масштабирования без дополнительной проверки.",
                limit=3,
            ),
        }

    if "raw/case_input.md" in missing_sources:
        default_sections["10"] += " Исходный сырой ввод отсутствует, поэтому часть исходного контекста реконструирована косвенно."

    parts = ["# Краткая управленческая записка", ""]
    for section in sections:
        idx = str(section.get("index", ""))
        title = str(section.get("title", ""))
        parts.extend([f"## {idx}. {title}", default_sections.get(idx, "Раздел ожидает уточнения по артефактам."), ""])
    parts.append("_Generated by local-llm mode._")
    return "\n".join(parts)


def _call_openai_responses(system_prompt: str, user_payload: Dict[str, Any]) -> str:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set")

    model = os.environ.get("OPENAI_MODEL", "gpt-4.1-mini")
    req_payload = {
        "model": model,
        "input": [
            {"role": "system", "content": [{"type": "input_text", "text": system_prompt}]},
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": json.dumps(user_payload, ensure_ascii=False),
                    }
                ],
            },
        ],
    }

    request = urllib.request.Request(
        "https://api.openai.com/v1/responses",
        data=json.dumps(req_payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    with urllib.request.urlopen(request, timeout=60) as resp:
        raw = json.loads(resp.read().decode("utf-8"))

    text = raw.get("output_text", "")
    if text:
        return text

    output = raw.get("output", [])
    if output and isinstance(output, list):
        for item in output:
            content = item.get("content", [])
            for block in content:
                txt = block.get("text")
                if txt:
                    return txt
    return ""


def _call_antigravity_adapter(system_prompt: str, user_payload: Dict[str, Any]) -> str:
    """
    Optional adapter for Antigravity-managed LLMs.
    Expects env ANTIGRAVITY_LLM_CMD with a shell command that reads JSON from stdin
    and returns markdown text to stdout.
    """
    cmd = os.environ.get("ANTIGRAVITY_LLM_CMD", "").strip()
    if not cmd:
        return ""

    req = {
        "system_prompt": system_prompt,
        "user_payload": user_payload,
    }
    proc = subprocess.run(
        cmd,
        input=json.dumps(req, ensure_ascii=False),
        text=True,
        shell=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        return ""
    return (proc.stdout or "").strip()


def _call_gemini_responses(system_prompt: str, user_payload: Dict[str, Any]) -> str:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY is not set")

    model = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash")
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
    
    req_payload = {
        "systemInstruction": {
            "parts": [{"text": system_prompt}]
        },
        "contents": [
            {
                "parts": [{"text": json.dumps(user_payload, ensure_ascii=False)}]
            }
        ],
        "generationConfig": {
            "temperature": 0.2
        }
    }

    request = urllib.request.Request(
        url,
        data=json.dumps(req_payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    max_retries = 5
    for attempt in range(max_retries):
        try:
            with urllib.request.urlopen(request, timeout=180) as resp:
                raw = json.loads(resp.read().decode("utf-8"))
            
            candidates = raw.get("candidates", [])
            if candidates:
                content = candidates[0].get("content", {})
                parts = content.get("parts", [])
                if parts:
                    return parts[0].get("text", "")
            return ""
            
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8", errors="ignore")
            if e.code in (429, 503):
                if attempt == 0:
                    print(f"  [API] Детали ошибки {e.code} от Google: {error_body.strip()[:200]}")
                wait_time = (attempt + 1) * 15  # 15s, 30s, 45s...
                print(f"  [API] Временно уперлись в лимит или сервер перегружен (Error {e.code}). Ждем {wait_time} сек... (Попытка {attempt+1}/{max_retries})")
                time.sleep(wait_time)
                continue
            else:
                print(f"Gemini API HTTP Error: {e.code} - {e.reason}\nBody: {error_body}")
                break
        except Exception as e:
            print(f"Gemini API error: {e}")
            if attempt < max_retries - 1:
                wait_time = (attempt + 1) * 15
                print(f"  [API] Сетевая ошибка или таймаут. Ждем {wait_time} сек... (Попытка {attempt+1}/{max_retries})")
                time.sleep(wait_time)
                continue
            break
        
    return ""


def generate_markdown_with_skill(
    system_skill_prompt: str,
    user_payload: Dict[str, Any],
    mode: str = "local",
) -> str:
    selected = (mode or "local").lower()
    task_type = str(user_payload.get("task_type", ""))

    if selected == "antigravity":
        text = _call_antigravity_adapter(system_skill_prompt, user_payload)
        if text.strip():
            return text

    if selected == "openai":
        text = _call_openai_responses(system_skill_prompt, user_payload)
        if text.strip():
            return text

    if selected == "gemini":
        text = _call_gemini_responses(system_skill_prompt, user_payload)
        if text.strip():
            return text

    if task_type == "build_layer":
        return _local_build_layer(user_payload)
    if task_type == "build_viewpoint":
        return _local_build_viewpoint(user_payload)
    if task_type == "build_characterization":
        return _local_build_characterization(user_payload)
    if task_type == "build_indicator_set":
        return _local_build_indicator_set(user_payload)
    if task_type == "build_parity_plan":
        return _local_build_parity_plan(user_payload)
    if task_type == "build_characteristic_card":
        return _local_build_characteristic_card(user_payload)
    if task_type == "build_problem_bundle":
        return _local_build_problem_bundle(user_payload)
    if task_type == "build_solution_portfolio":
        return _local_build_solution_portfolio(user_payload)
    if task_type == "build_parity_tradeoff":
        return _local_build_parity_tradeoff(user_payload)
    if task_type == "build_conflict_routing":
        return _local_build_conflict_routing(user_payload)
    if task_type == "build_selection_bundle":
        return _local_build_selection_bundle(user_payload)
    if task_type == "build_reporting_analytical":
        return _local_build_reporting_analytical(user_payload)
    if task_type == "build_reporting_executive":
        return _local_build_reporting_executive(user_payload)

    return "# Generated Artifact\n\n- No task-specific local renderer configured.\n\n_Generated by local-llm mode._"
